<?php

namespace SME\DGPPermutaBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class IntencaoController__JMSInjector
{
    public static function inject($container) {
        $instance = new \SME\DGPPermutaBundle\Controller\IntencaoController();
        return $instance;
    }
}
