<?php

namespace SME\DGPBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class TelefoneController__JMSInjector
{
    public static function inject($container) {
        $instance = new \SME\DGPBundle\Controller\TelefoneController();
        return $instance;
    }
}
