<?php

namespace SME\FilaUnicaBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class MovimentacaoInternaController__JMSInjector
{
    public static function inject($container) {
        $instance = new \SME\FilaUnicaBundle\Controller\MovimentacaoInternaController();
        return $instance;
    }
}
