(function (){
    //LISTANDO TODOS OS MODULOS
    var configs = [
        'erudioConfig',
        'auth',
        'rest',
        'util',
        'structure',
        'validator',
        'shared',
        'home'
    ];
    
    var controllers = [
        'InstituicaoController',
        'instituicoesForm',
        'tipoUnidade',
        'tipoUnidadeForm',
        'unidades',
        'unidadesForm',
        'regimes',
        'regimesForm',
        'cursos',
        'cursosForm',
        'etapas',
        'etapasForm',
        'disciplinas',
        'disciplinasForm',
        'modulos',
        'modulosForm',
        'turnos',
        'turnosForm',
        'modelosGradeHorario',
        'modelosGradeHorarioForm',
        'quadroHorarios',
        'quadroHorariosForm',
        'calendarios',
        'calendariosForm',
        'calendariosView',
        'teste'
    ];
    
    var directives = [
        'instituicaoDirectives',
        'tipoUnidadeDirectives',
        'unidadeDirectives',
        'regimeDirectives',
        'cursoDirectives',
        'etapaDirectives',
        'disciplinaDirectives',
        'moduloDirectives',
        'turnoDirectives',
        'modelosGradeHorarioDirectives',
        'quadroHorarioDirectives',
        'calendarioDirectives',
        'eventoDirectives',
        'turmaDirectives',
        'cargosDirectives',
        'tipoAvaliacaoDirectives',
        'habilidadeDirectives',
        'avaliacaoDirectives',
        'grupoDirectives',
        'grupoPermissaoDirectives',
        'usuarioDirectives'
    ];
    
    var services = [
        'BaseService',
        'EnderecoService',
        'TelefoneService',
        'InstituicaoService',
        'TipoUnidadeService',
        'CursoOfertadoService',
        'UnidadeService',
        'RegimeService',
        'ModalidadeEnsinoService',
        'CursoService',
        'EtapaService',
        'ModuloService',
        'SistemaAvaliacaoService',
        'ModeloGradeHorarioService',
        'DisciplinaService',
        'TurnoService',
        'QuadroHorarioService',
        'CalendarioService',
        'EventoService',
        'PeriodoService',
        'TurmaService',
        'MatriculaService',
        'EnturmacaoService',
        'TransferenciaService',
        'DesligamentoService',
        'MovimentacaoService',
        'EstadoCivilService',
        'RacaService',
        'NacionalidadeService',
        'ParticularidadeService',
        'NecessidadeEspecialService',
        'PessoaService',
        'GrupoService',
        'CargoService',
        'TipoAvaliacaoService',
        'HabilidadeService',
        'AvaliacaoService',
        'GrupoPermissaoService',
        'GrupoService',
        'PermissaoGrupoService',
        'AtribuicaoService',
        'PermissaoService',
        'UsuarioService'
    ];
    
    var todosModulos = configs.concat(services,controllers,directives);
    var modules = angular.module('modules',todosModulos);
})();