<?php declare(strict_types = 1);

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20180103152131 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE edu_acesso_atribuicao (id INT AUTO_INCREMENT NOT NULL, usuario_id INT NOT NULL, grupo_id INT NOT NULL, instituicao_id INT NOT NULL, apelido VARCHAR(255) NOT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, INDEX IDX_E55ADF3DDB38439E (usuario_id), INDEX IDX_E55ADF3D9C833003 (grupo_id), INDEX IDX_E55ADF3DB05E5EEA (instituicao_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_acesso_grupo (id INT AUTO_INCREMENT NOT NULL, nome VARCHAR(255) NOT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_acesso_permissao (id INT AUTO_INCREMENT NOT NULL, nome VARCHAR(255) NOT NULL, nome_exibicao VARCHAR(255) NOT NULL, ativo TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_acesso_permissao_grupo (id INT AUTO_INCREMENT NOT NULL, permissao_id INT NOT NULL, grupo_id INT NOT NULL, tipo VARCHAR(1) NOT NULL, ativo TINYINT(1) NOT NULL, INDEX IDX_ED390447E009E574 (permissao_id), INDEX IDX_ED3904479C833003 (grupo_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_acesso_usuario (id INT AUTO_INCREMENT NOT NULL, nome_usuario VARCHAR(255) NOT NULL, senha VARCHAR(255) NOT NULL, nome_exibicao VARCHAR(255) NOT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sme_pessoa (id INT AUTO_INCREMENT NOT NULL, endereco_id INT DEFAULT NULL, usuario_id INT DEFAULT NULL, nome VARCHAR(255) NOT NULL, cpf_cnpj VARCHAR(14) NOT NULL, data_nascimento DATE NOT NULL, email VARCHAR(200) DEFAULT NULL, genero VARCHAR(1) NOT NULL, inep VARCHAR(255) DEFAULT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, tipo_pessoa VARCHAR(255) NOT NULL, INDEX IDX_B3530DBE1BB76823 (endereco_id), UNIQUE INDEX UNIQ_B3530DBEDB38439E (usuario_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sme_particularidade (id INT AUTO_INCREMENT NOT NULL, nome VARCHAR(255) NOT NULL, tipo VARCHAR(255) NOT NULL, ativo TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sme_raca (id INT AUTO_INCREMENT NOT NULL, nome VARCHAR(255) NOT NULL, ativo TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sme_pessoa_juridica (id INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_instituicao (id INT NOT NULL, instituicao_pai_id INT DEFAULT NULL, INDEX IDX_CD57CCD222EAC624 (instituicao_pai_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_unidade_ensino (id INT NOT NULL, tipo_id INT NOT NULL, INDEX IDX_C03EFDE1A9276E6C (tipo_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_tipo_unidade_ensino (id INT AUTO_INCREMENT NOT NULL, nome VARCHAR(255) NOT NULL, sigla VARCHAR(255) NOT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sme_necessidade_especial (id INT AUTO_INCREMENT NOT NULL, nome VARCHAR(255) NOT NULL, ativo TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sme_pessoa_telefone (id INT AUTO_INCREMENT NOT NULL, pessoa_id INT NOT NULL, numero VARCHAR(50) NOT NULL, descricao VARCHAR(255) NOT NULL, falar_com VARCHAR(255) DEFAULT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, INDEX IDX_9A323A2EDF6FA0A5 (pessoa_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sme_estado (id INT AUTO_INCREMENT NOT NULL, pais_id INT NOT NULL, nome VARCHAR(255) NOT NULL, sigla VARCHAR(255) NOT NULL, ativo TINYINT(1) NOT NULL, INDEX IDX_89D147DFC604D5C6 (pais_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sme_estado_civil (id INT AUTO_INCREMENT NOT NULL, nome VARCHAR(255) NOT NULL, ativo TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_beneficio_social (id INT AUTO_INCREMENT NOT NULL, nome VARCHAR(255) NOT NULL, ativo TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sme_pessoa_fisica (id INT NOT NULL, pais_nacionalidade_id INT DEFAULT NULL, cidade_nascimento_id INT DEFAULT NULL, estado_civil_id INT NOT NULL, raca_id INT NOT NULL, carteira_trabalho_estado_id INT DEFAULT NULL, rg_numero VARCHAR(255) DEFAULT NULL, rg_orgao_expedidor VARCHAR(255) DEFAULT NULL, rg_data_expedicao DATE DEFAULT NULL, nis VARCHAR(255) DEFAULT NULL, pis_pasep VARCHAR(255) DEFAULT NULL, cns VARCHAR(255) DEFAULT NULL, nacionalidade_tipo VARCHAR(255) NOT NULL, certidao_nascimento_completa VARCHAR(32) DEFAULT NULL, certidao_nascimento_data_expedicao DATE DEFAULT NULL, mae_nome VARCHAR(255) DEFAULT NULL, pai_nome VARCHAR(255) DEFAULT NULL, responsavel_nome VARCHAR(255) DEFAULT NULL, carteira_trabalho_numero VARCHAR(255) DEFAULT NULL, carteira_trabalho_serie VARCHAR(255) DEFAULT NULL, carteira_trabalho_data_expedicao DATE DEFAULT NULL, alfabetizado TINYINT(1) NOT NULL, INDEX IDX_F4375A60F46BFC5F (pais_nacionalidade_id), INDEX IDX_F4375A60737AA82E (cidade_nascimento_id), INDEX IDX_F4375A6075376D93 (estado_civil_id), INDEX IDX_F4375A60E13B435A (raca_id), INDEX IDX_F4375A60ABDA9359 (carteira_trabalho_estado_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sme_pessoa_fisica_particularidade (pessoa_fisica_id INT NOT NULL, particularidade_id INT NOT NULL, INDEX IDX_96A1CA5E8679B4F7 (pessoa_fisica_id), INDEX IDX_96A1CA5E938C9B05 (particularidade_id), PRIMARY KEY(pessoa_fisica_id, particularidade_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sme_pessoa_fisica_necessidade_especial (pessoa_fisica_id INT NOT NULL, necessidade_especial_id INT NOT NULL, INDEX IDX_24240AD98679B4F7 (pessoa_fisica_id), INDEX IDX_24240AD9349DA9B6 (necessidade_especial_id), PRIMARY KEY(pessoa_fisica_id, necessidade_especial_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_pessoa_fisica_beneficio_social (pessoa_fisica_id INT NOT NULL, beneficio_social_id INT NOT NULL, INDEX IDX_354784D88679B4F7 (pessoa_fisica_id), INDEX IDX_354784D86184F2DF (beneficio_social_id), PRIMARY KEY(pessoa_fisica_id, beneficio_social_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sme_cidade (id INT AUTO_INCREMENT NOT NULL, estado_id INT NOT NULL, nome VARCHAR(255) NOT NULL, sigla VARCHAR(255) DEFAULT NULL, ibge VARCHAR(255) DEFAULT NULL, ativo TINYINT(1) NOT NULL, INDEX IDX_C51495609F5A440B (estado_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sme_pais (id INT AUTO_INCREMENT NOT NULL, iso VARCHAR(255) DEFAULT NULL, iso3 VARCHAR(255) DEFAULT NULL, codigo VARCHAR(255) DEFAULT NULL, nome VARCHAR(255) NOT NULL, ativo TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sme_endereco (id INT AUTO_INCREMENT NOT NULL, cidade_id INT NOT NULL, logradouro VARCHAR(255) NOT NULL, numero INT DEFAULT NULL, complemento VARCHAR(255) DEFAULT NULL, cep VARCHAR(8) NOT NULL, bairro VARCHAR(255) DEFAULT NULL, latitude VARCHAR(255) DEFAULT NULL, longitude VARCHAR(255) DEFAULT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, INDEX IDX_B4A606A09586CC8 (cidade_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_turma_disciplina (id INT AUTO_INCREMENT NOT NULL, turma_id INT NOT NULL, disciplina_id INT NOT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, INDEX IDX_9D020B06CEBA2CFD (turma_id), INDEX IDX_9D020B062A30B056 (disciplina_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_turma_disciplina_alocacao (turma_disciplina_id INT NOT NULL, alocacao_id INT NOT NULL, INDEX IDX_4C721EF749A116CA (turma_disciplina_id), INDEX IDX_4C721EF7110E6AE8 (alocacao_id), PRIMARY KEY(turma_disciplina_id, alocacao_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_turma (id INT AUTO_INCREMENT NOT NULL, unidade_ensino_id INT NOT NULL, etapa_id INT NOT NULL, turno_id INT NOT NULL, calendario_id INT NOT NULL, calendario_periodo_id INT DEFAULT NULL, quadro_horario_id INT NOT NULL, turma_agrupamento_id INT DEFAULT NULL, disciplina_agrupamento_id INT DEFAULT NULL, nome VARCHAR(255) NOT NULL, apelido VARCHAR(255) DEFAULT NULL, status VARCHAR(255) NOT NULL, limite_alunos INT NOT NULL, data_encerramento DATETIME DEFAULT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, INDEX IDX_AF4D5118D0F99DE (unidade_ensino_id), INDEX IDX_AF4D511C5EE35FA (etapa_id), INDEX IDX_AF4D51169C5211E (turno_id), INDEX IDX_AF4D511A7F6EA19 (calendario_id), INDEX IDX_AF4D511F304037D (calendario_periodo_id), INDEX IDX_AF4D511208D8E23 (quadro_horario_id), INDEX IDX_AF4D511E6EF7188 (turma_agrupamento_id), INDEX IDX_AF4D511AA7B4B22 (disciplina_agrupamento_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_sistema_avaliacao (id INT AUTO_INCREMENT NOT NULL, regime_id INT NOT NULL, nome VARCHAR(255) NOT NULL, nome_identificacao VARCHAR(255) NOT NULL, tipo VARCHAR(255) NOT NULL, quantidade_medias INT NOT NULL, nota_aprovacao DOUBLE PRECISION NOT NULL, frequencia_minima DOUBLE PRECISION NOT NULL, hora_aula DOUBLE PRECISION NOT NULL, exame TINYINT(1) NOT NULL, peso_exame INT DEFAULT NULL, nota_aprovacao_exame DOUBLE PRECISION DEFAULT NULL, ativo TINYINT(1) NOT NULL, INDEX IDX_2E72CC6035E7D534 (regime_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_unidade_ensino_curso (id INT AUTO_INCREMENT NOT NULL, unidade_ensino_id INT NOT NULL, curso_id INT NOT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, INDEX IDX_ACE4E9698D0F99DE (unidade_ensino_id), INDEX IDX_ACE4E96987CB4A1F (curso_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_regime (id INT AUTO_INCREMENT NOT NULL, nome VARCHAR(255) NOT NULL, unidade VARCHAR(255) NOT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_turno (id INT AUTO_INCREMENT NOT NULL, nome VARCHAR(255) NOT NULL, inicio TIME NOT NULL, termino TIME NOT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_modalidade_ensino (id INT AUTO_INCREMENT NOT NULL, nome VARCHAR(255) NOT NULL, ativo TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_disciplina (id INT AUTO_INCREMENT NOT NULL, etapa_id INT DEFAULT NULL, curso_id INT NOT NULL, disciplina_agrupamento_id INT DEFAULT NULL, nome VARCHAR(255) NOT NULL, nome_exibicao VARCHAR(255) NOT NULL, sigla VARCHAR(255) NOT NULL, carga_horaria INT NOT NULL, opcional TINYINT(1) NOT NULL, ofertado TINYINT(1) NOT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, INDEX IDX_D179B51DC5EE35FA (etapa_id), INDEX IDX_D179B51D87CB4A1F (curso_id), INDEX IDX_D179B51DAA7B4B22 (disciplina_agrupamento_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_etapa (id INT AUTO_INCREMENT NOT NULL, modulo_id INT DEFAULT NULL, curso_id INT NOT NULL, quadro_horario_modelo_id INT NOT NULL, sistema_avaliacao_id INT NOT NULL, nome VARCHAR(255) NOT NULL, nome_exibicao VARCHAR(255) NOT NULL, ordem INT NOT NULL, limite_alunos INT NOT NULL, idade_recomendada INT DEFAULT NULL, integral TINYINT(1) NOT NULL, frequencia_unificada TINYINT(1) NOT NULL, observacao_aprovacao VARCHAR(255) DEFAULT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, INDEX IDX_EC47D73C07F55F5 (modulo_id), INDEX IDX_EC47D7387CB4A1F (curso_id), INDEX IDX_EC47D732F0688B4 (quadro_horario_modelo_id), INDEX IDX_EC47D733F2340FB (sistema_avaliacao_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_disciplina_agrupamento (id INT AUTO_INCREMENT NOT NULL, etapa_id INT NOT NULL, nome VARCHAR(255) NOT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, INDEX IDX_8E787AB7C5EE35FA (etapa_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_curso (id INT AUTO_INCREMENT NOT NULL, instituicao_id INT NOT NULL, modalidade_ensino_id INT NOT NULL, nome VARCHAR(255) NOT NULL, alfabetizatorio TINYINT(1) NOT NULL, limite_defasagem INT NOT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, INDEX IDX_EBCD8C5BB05E5EEA (instituicao_id), INDEX IDX_EBCD8C5BF5E98D2B (modalidade_ensino_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_turma_agrupamento (id INT AUTO_INCREMENT NOT NULL, unidade_ensino_id INT NOT NULL, nome VARCHAR(255) NOT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, INDEX IDX_5E0FFC5B8D0F99DE (unidade_ensino_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_modulo (id INT AUTO_INCREMENT NOT NULL, curso_id INT NOT NULL, nome VARCHAR(255) NOT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, INDEX IDX_B9D51FD587CB4A1F (curso_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_quadro_horario_modelo (id INT AUTO_INCREMENT NOT NULL, curso_id INT NOT NULL, nome VARCHAR(255) NOT NULL, quantidade_aulas INT NOT NULL, duracao_aula INT NOT NULL, duracao_intervalo INT NOT NULL, posicao_intervalo INT NOT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, INDEX IDX_A1D49A5387CB4A1F (curso_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_calendario_periodo (id INT AUTO_INCREMENT NOT NULL, calendario_id INT NOT NULL, media VARCHAR(255) NOT NULL, data_inicio DATE NOT NULL, data_termino DATE NOT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, INDEX IDX_6F094727A7F6EA19 (calendario_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_calendario (id INT AUTO_INCREMENT NOT NULL, instituicao_id INT NOT NULL, calendario_base_id INT DEFAULT NULL, nome VARCHAR(255) NOT NULL, data_inicio DATE NOT NULL, data_termino DATE NOT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, INDEX IDX_8CB334B7B05E5EEA (instituicao_id), INDEX IDX_8CB334B73B5FC2BB (calendario_base_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_calendario_evento_dia (id INT AUTO_INCREMENT NOT NULL, dia_id INT NOT NULL, evento_id INT NOT NULL, inicio TIME NOT NULL, termino TIME NOT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, INDEX IDX_CC0A03EEAC1F7597 (dia_id), INDEX IDX_CC0A03EE87A5F842 (evento_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_calendario_evento (id INT AUTO_INCREMENT NOT NULL, nome VARCHAR(255) NOT NULL, descricao VARCHAR(255) DEFAULT NULL, tipo VARCHAR(255) NOT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_calendario_dia (id INT AUTO_INCREMENT NOT NULL, calendario_id INT NOT NULL, data_dia DATE NOT NULL, letivo TINYINT(1) NOT NULL, efetivo TINYINT(1) NOT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, INDEX IDX_FB5F2B2BA7F6EA19 (calendario_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_quadro_horario (id INT AUTO_INCREMENT NOT NULL, modelo_id INT DEFAULT NULL, unidade_ensino_id INT DEFAULT NULL, turno_id INT DEFAULT NULL, nome VARCHAR(255) NOT NULL, turno_inicio TIME NOT NULL, turno_termino TIME NOT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, INDEX IDX_1AFC7185C3A9576E (modelo_id), INDEX IDX_1AFC71858D0F99DE (unidade_ensino_id), INDEX IDX_1AFC718569C5211E (turno_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_quadro_horario_dia_semana (id INT AUTO_INCREMENT NOT NULL, quadro_horario_id INT NOT NULL, dia_semana VARCHAR(255) NOT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, INDEX IDX_7EA346EA208D8E23 (quadro_horario_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_quadro_horario_aula_turma (id INT AUTO_INCREMENT NOT NULL, turma_disciplina_id INT DEFAULT NULL, quadro_horario_aula_id INT DEFAULT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, INDEX IDX_3C29BDF049A116CA (turma_disciplina_id), INDEX IDX_3C29BDF08C9146E1 (quadro_horario_aula_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_quadro_horario_aula (id INT AUTO_INCREMENT NOT NULL, quadro_horario_dia_semana_id INT NOT NULL, quadro_horario_id INT NOT NULL, inicio TIME NOT NULL, termino TIME NOT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, INDEX IDX_F84A68CBA6EBF416 (quadro_horario_dia_semana_id), INDEX IDX_F84A68CB208D8E23 (quadro_horario_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_avaliacao_tipo (id INT AUTO_INCREMENT NOT NULL, nome VARCHAR(255) NOT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_avaliacao (id INT AUTO_INCREMENT NOT NULL, turma_disciplina_id INT NOT NULL, nome VARCHAR(255) NOT NULL, media INT NOT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, tipo_avaliacao VARCHAR(255) NOT NULL, INDEX IDX_7F84084049A116CA (turma_disciplina_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_avaliacao_qualitativa (id INT NOT NULL, tipo VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_avaliacao_habilidade (id INT AUTO_INCREMENT NOT NULL, disciplina_id INT NOT NULL, nome VARCHAR(255) NOT NULL, media INT NOT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, INDEX IDX_24534CD32A30B056 (disciplina_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_avaliacao_conceito (id INT AUTO_INCREMENT NOT NULL, nome VARCHAR(255) NOT NULL, sigla VARCHAR(255) NOT NULL, valor_min DOUBLE PRECISION NOT NULL, valor_max DOUBLE PRECISION NOT NULL, ativo TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_avaliacao_quantitativa (id INT NOT NULL, tipo_id INT NOT NULL, peso INT NOT NULL, data_entrega DATETIME DEFAULT NULL, INDEX IDX_22351265A9276E6C (tipo_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_aula (id INT AUTO_INCREMENT NOT NULL, turma_id INT NOT NULL, dia_id INT NOT NULL, quadro_horario_aula_id INT DEFAULT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, INDEX IDX_41219290CEBA2CFD (turma_id), INDEX IDX_41219290AC1F7597 (dia_id), INDEX IDX_412192908C9146E1 (quadro_horario_aula_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_aula_turma_disciplina (aula_id INT NOT NULL, turma_disciplina_id INT NOT NULL, INDEX IDX_8DEF7428AD1A1255 (aula_id), INDEX IDX_8DEF742849A116CA (turma_disciplina_id), PRIMARY KEY(aula_id, turma_disciplina_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_aula_anotacao (id INT AUTO_INCREMENT NOT NULL, aula_id INT NOT NULL, observacao VARCHAR(255) NOT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, INDEX IDX_1BC42F77AD1A1255 (aula_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_aula_frequencia (id INT AUTO_INCREMENT NOT NULL, aula_id INT NOT NULL, status VARCHAR(255) NOT NULL, justificativa VARCHAR(255) DEFAULT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, INDEX IDX_29529F1FAD1A1255 (aula_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_aula_frequencia_matricula_disciplina (frequencia_id INT NOT NULL, matricula_disciplina_id INT NOT NULL, INDEX IDX_1E91CAE9A87573C7 (frequencia_id), INDEX IDX_1E91CAE99D3DC654 (matricula_disciplina_id), PRIMARY KEY(frequencia_id, matricula_disciplina_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_nota (id INT AUTO_INCREMENT NOT NULL, media_id INT NOT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, tipo_nota VARCHAR(255) NOT NULL, INDEX IDX_8AE83C39EA9FDD75 (media_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_nota_quantitativa (id INT NOT NULL, avaliacao_quantitativa_id INT NOT NULL, valor DOUBLE PRECISION NOT NULL, INDEX IDX_A4D02A50813F7652 (avaliacao_quantitativa_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_nota_qualitativa (id INT NOT NULL, avaliacao_qualitativa_id INT NOT NULL, INDEX IDX_6050A232116A2E6D (avaliacao_qualitativa_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_matricula_historico_observacao (id INT AUTO_INCREMENT NOT NULL, matricula_id INT NOT NULL, texto VARCHAR(255) NOT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, INDEX IDX_E22C9FC115C84B52 (matricula_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_movimentacao (id INT AUTO_INCREMENT NOT NULL, matricula_id INT NOT NULL, justificativa VARCHAR(255) NOT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, tipo_movimentacao VARCHAR(255) NOT NULL, INDEX IDX_9DBDF42D15C84B52 (matricula_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_movimentacao_turma (id INT NOT NULL, enturmacao_origem_id INT NOT NULL, enturmacao_destino_id INT NOT NULL, INDEX IDX_BD6FA8ABBD47951F (enturmacao_origem_id), INDEX IDX_BD6FA8ABCB65DA36 (enturmacao_destino_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_movimentacao_transferencia (id INT NOT NULL, unidade_ensino_origem_id INT NOT NULL, unidade_ensino_destino_id INT NOT NULL, status VARCHAR(255) NOT NULL, data_agendamento DATE NOT NULL, data_encerramento DATETIME DEFAULT NULL, resposta VARCHAR(255) DEFAULT NULL, INDEX IDX_1AE9B8C1215A5E9 (unidade_ensino_origem_id), INDEX IDX_1AE9B8C19F04DF2F (unidade_ensino_destino_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_enturmacao (id INT AUTO_INCREMENT NOT NULL, matricula_id INT NOT NULL, turma_id INT NOT NULL, encerrado TINYINT(1) NOT NULL, concluido TINYINT(1) NOT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, INDEX IDX_3AADDEAF15C84B52 (matricula_id), INDEX IDX_3AADDEAFCEBA2CFD (turma_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_movimentacao_reclassificacao_nota (id INT AUTO_INCREMENT NOT NULL, reclassificacao_id INT NOT NULL, disciplina_id INT NOT NULL, valor DOUBLE PRECISION NOT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, INDEX IDX_EC786B85DAE4A065 (reclassificacao_id), INDEX IDX_EC786B852A30B056 (disciplina_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_media (id INT AUTO_INCREMENT NOT NULL, matricula_disciplina_id INT NOT NULL, nome VARCHAR(255) NOT NULL, numero INT NOT NULL, valor VARCHAR(255) DEFAULT NULL, peso VARCHAR(255) NOT NULL, faltas VARCHAR(255) NOT NULL, frequencia DOUBLE PRECISION DEFAULT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, INDEX IDX_4BDA6DBB9D3DC654 (matricula_disciplina_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_movimentacao_retorno (id INT NOT NULL, unidade_ensino_id INT NOT NULL, etapa_id INT NOT NULL, origem VARCHAR(255) NOT NULL, INDEX IDX_A97BCC2B8D0F99DE (unidade_ensino_id), INDEX IDX_A97BCC2BC5EE35FA (etapa_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_nota_qualitativa_habilidade (id INT AUTO_INCREMENT NOT NULL, habilidade_id INT NOT NULL, conceito_id INT NOT NULL, nota_qualitativa_id INT DEFAULT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, INDEX IDX_D0170E4BFDD1D822 (habilidade_id), INDEX IDX_D0170E4B48FA63EE (conceito_id), INDEX IDX_D0170E4B90636C03 (nota_qualitativa_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_uniforme (id INT AUTO_INCREMENT NOT NULL, matricula_id INT NOT NULL, uniforme_numero VARCHAR(255) NOT NULL, calcado_numero VARCHAR(255) NOT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, INDEX IDX_49A957D315C84B52 (matricula_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_movimentacao_desligamento (id INT NOT NULL, motivo VARCHAR(255) NOT NULL, destino VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_matricula_etapa (id INT AUTO_INCREMENT NOT NULL, matricula_id INT NOT NULL, etapa_id INT NOT NULL, cidade_id INT NOT NULL, enturmacao_id INT DEFAULT NULL, ano INT NOT NULL, unidade_ensino VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, insercao_manual TINYINT(1) NOT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, INDEX IDX_BD2A83DD15C84B52 (matricula_id), INDEX IDX_BD2A83DDC5EE35FA (etapa_id), INDEX IDX_BD2A83DD9586CC8 (cidade_id), UNIQUE INDEX UNIQ_BD2A83DDEB5D3E62 (enturmacao_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_matricula_disciplina (id INT AUTO_INCREMENT NOT NULL, matricula_id INT NOT NULL, disciplina_id INT NOT NULL, enturmacao_id INT DEFAULT NULL, turma_disciplina_id INT DEFAULT NULL, status VARCHAR(255) NOT NULL, media_final VARCHAR(255) DEFAULT NULL, frequencia_total DOUBLE PRECISION DEFAULT NULL, ano INT NOT NULL, data_encerramento DATETIME DEFAULT NULL, insercao_manual TINYINT(1) NOT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, INDEX IDX_1443F5AF15C84B52 (matricula_id), INDEX IDX_1443F5AF2A30B056 (disciplina_id), INDEX IDX_1443F5AFEB5D3E62 (enturmacao_id), INDEX IDX_1443F5AF49A116CA (turma_disciplina_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_matricula (id INT AUTO_INCREMENT NOT NULL, pessoa_fisica_aluno_id INT NOT NULL, curso_id INT NOT NULL, etapa_id INT DEFAULT NULL, unidade_ensino_id INT NOT NULL, codigo VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, data_encerramento DATETIME DEFAULT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, INDEX IDX_34057E7C83F5509 (pessoa_fisica_aluno_id), INDEX IDX_34057E787CB4A1F (curso_id), INDEX IDX_34057E7C5EE35FA (etapa_id), INDEX IDX_34057E78D0F99DE (unidade_ensino_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_movimentacao_reclassificacao (id INT NOT NULL, enturmacao_origem_id INT NOT NULL, enturmacao_destino_id INT NOT NULL, INDEX IDX_79406D86BD47951F (enturmacao_origem_id), INDEX IDX_79406D86CB65DA36 (enturmacao_destino_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_vinculo (id INT AUTO_INCREMENT NOT NULL, pessoa_fisica_funcionario_id INT NOT NULL, cargo_id INT NOT NULL, instituicao_id INT NOT NULL, codigo VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, tipo_contrato VARCHAR(255) NOT NULL, carga_horaria INT NOT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, INDEX IDX_4D9790F7E2D44972 (pessoa_fisica_funcionario_id), INDEX IDX_4D9790F7813AC380 (cargo_id), INDEX IDX_4D9790F7B05E5EEA (instituicao_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_cargo (id INT AUTO_INCREMENT NOT NULL, acesso_grupo_id INT DEFAULT NULL, nome VARCHAR(255) NOT NULL, professor TINYINT(1) NOT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, INDEX IDX_1A189BC68FC40795 (acesso_grupo_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_alocacao (id INT AUTO_INCREMENT NOT NULL, vinculo_id INT NOT NULL, instituicao_id INT NOT NULL, carga_horaria INT NOT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, INDEX IDX_89250D206A4AB3EE (vinculo_id), INDEX IDX_89250D20B05E5EEA (instituicao_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edu_vaga (id INT AUTO_INCREMENT NOT NULL, turma_id INT NOT NULL, enturmacao_id INT NOT NULL, data_cadastro DATETIME NOT NULL, data_modificacao DATETIME DEFAULT NULL, data_exclusao DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, INDEX IDX_74342FD1CEBA2CFD (turma_id), UNIQUE INDEX UNIQ_74342FD1EB5D3E62 (enturmacao_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE edu_acesso_atribuicao ADD CONSTRAINT FK_E55ADF3DDB38439E FOREIGN KEY (usuario_id) REFERENCES edu_acesso_usuario (id)');
        $this->addSql('ALTER TABLE edu_acesso_atribuicao ADD CONSTRAINT FK_E55ADF3D9C833003 FOREIGN KEY (grupo_id) REFERENCES edu_acesso_grupo (id)');
        $this->addSql('ALTER TABLE edu_acesso_atribuicao ADD CONSTRAINT FK_E55ADF3DB05E5EEA FOREIGN KEY (instituicao_id) REFERENCES edu_instituicao (id)');
        $this->addSql('ALTER TABLE edu_acesso_permissao_grupo ADD CONSTRAINT FK_ED390447E009E574 FOREIGN KEY (permissao_id) REFERENCES edu_acesso_permissao (id)');
        $this->addSql('ALTER TABLE edu_acesso_permissao_grupo ADD CONSTRAINT FK_ED3904479C833003 FOREIGN KEY (grupo_id) REFERENCES edu_acesso_grupo (id)');
        $this->addSql('ALTER TABLE sme_pessoa ADD CONSTRAINT FK_B3530DBE1BB76823 FOREIGN KEY (endereco_id) REFERENCES sme_endereco (id)');
        $this->addSql('ALTER TABLE sme_pessoa ADD CONSTRAINT FK_B3530DBEDB38439E FOREIGN KEY (usuario_id) REFERENCES edu_acesso_usuario (id)');
        $this->addSql('ALTER TABLE sme_pessoa_juridica ADD CONSTRAINT FK_74B6057EBF396750 FOREIGN KEY (id) REFERENCES sme_pessoa (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE edu_instituicao ADD CONSTRAINT FK_CD57CCD222EAC624 FOREIGN KEY (instituicao_pai_id) REFERENCES edu_instituicao (id)');
        $this->addSql('ALTER TABLE edu_instituicao ADD CONSTRAINT FK_CD57CCD2BF396750 FOREIGN KEY (id) REFERENCES sme_pessoa (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE edu_unidade_ensino ADD CONSTRAINT FK_C03EFDE1A9276E6C FOREIGN KEY (tipo_id) REFERENCES edu_tipo_unidade_ensino (id)');
        $this->addSql('ALTER TABLE edu_unidade_ensino ADD CONSTRAINT FK_C03EFDE1BF396750 FOREIGN KEY (id) REFERENCES sme_pessoa (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sme_pessoa_telefone ADD CONSTRAINT FK_9A323A2EDF6FA0A5 FOREIGN KEY (pessoa_id) REFERENCES sme_pessoa (id)');
        $this->addSql('ALTER TABLE sme_estado ADD CONSTRAINT FK_89D147DFC604D5C6 FOREIGN KEY (pais_id) REFERENCES sme_pais (id)');
        $this->addSql('ALTER TABLE sme_pessoa_fisica ADD CONSTRAINT FK_F4375A60F46BFC5F FOREIGN KEY (pais_nacionalidade_id) REFERENCES sme_pais (id)');
        $this->addSql('ALTER TABLE sme_pessoa_fisica ADD CONSTRAINT FK_F4375A60737AA82E FOREIGN KEY (cidade_nascimento_id) REFERENCES sme_cidade (id)');
        $this->addSql('ALTER TABLE sme_pessoa_fisica ADD CONSTRAINT FK_F4375A6075376D93 FOREIGN KEY (estado_civil_id) REFERENCES sme_estado_civil (id)');
        $this->addSql('ALTER TABLE sme_pessoa_fisica ADD CONSTRAINT FK_F4375A60E13B435A FOREIGN KEY (raca_id) REFERENCES sme_raca (id)');
        $this->addSql('ALTER TABLE sme_pessoa_fisica ADD CONSTRAINT FK_F4375A60ABDA9359 FOREIGN KEY (carteira_trabalho_estado_id) REFERENCES sme_estado (id)');
        $this->addSql('ALTER TABLE sme_pessoa_fisica ADD CONSTRAINT FK_F4375A60BF396750 FOREIGN KEY (id) REFERENCES sme_pessoa (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sme_pessoa_fisica_particularidade ADD CONSTRAINT FK_96A1CA5E8679B4F7 FOREIGN KEY (pessoa_fisica_id) REFERENCES sme_pessoa_fisica (id)');
        $this->addSql('ALTER TABLE sme_pessoa_fisica_particularidade ADD CONSTRAINT FK_96A1CA5E938C9B05 FOREIGN KEY (particularidade_id) REFERENCES sme_particularidade (id)');
        $this->addSql('ALTER TABLE sme_pessoa_fisica_necessidade_especial ADD CONSTRAINT FK_24240AD98679B4F7 FOREIGN KEY (pessoa_fisica_id) REFERENCES sme_pessoa_fisica (id)');
        $this->addSql('ALTER TABLE sme_pessoa_fisica_necessidade_especial ADD CONSTRAINT FK_24240AD9349DA9B6 FOREIGN KEY (necessidade_especial_id) REFERENCES sme_necessidade_especial (id)');
        $this->addSql('ALTER TABLE edu_pessoa_fisica_beneficio_social ADD CONSTRAINT FK_354784D88679B4F7 FOREIGN KEY (pessoa_fisica_id) REFERENCES sme_pessoa_fisica (id)');
        $this->addSql('ALTER TABLE edu_pessoa_fisica_beneficio_social ADD CONSTRAINT FK_354784D86184F2DF FOREIGN KEY (beneficio_social_id) REFERENCES edu_beneficio_social (id)');
        $this->addSql('ALTER TABLE sme_cidade ADD CONSTRAINT FK_C51495609F5A440B FOREIGN KEY (estado_id) REFERENCES sme_estado (id)');
        $this->addSql('ALTER TABLE sme_endereco ADD CONSTRAINT FK_B4A606A09586CC8 FOREIGN KEY (cidade_id) REFERENCES sme_cidade (id)');
        $this->addSql('ALTER TABLE edu_turma_disciplina ADD CONSTRAINT FK_9D020B06CEBA2CFD FOREIGN KEY (turma_id) REFERENCES edu_turma (id)');
        $this->addSql('ALTER TABLE edu_turma_disciplina ADD CONSTRAINT FK_9D020B062A30B056 FOREIGN KEY (disciplina_id) REFERENCES edu_disciplina (id)');
        $this->addSql('ALTER TABLE edu_turma_disciplina_alocacao ADD CONSTRAINT FK_4C721EF749A116CA FOREIGN KEY (turma_disciplina_id) REFERENCES edu_turma_disciplina (id)');
        $this->addSql('ALTER TABLE edu_turma_disciplina_alocacao ADD CONSTRAINT FK_4C721EF7110E6AE8 FOREIGN KEY (alocacao_id) REFERENCES edu_alocacao (id)');
        $this->addSql('ALTER TABLE edu_turma ADD CONSTRAINT FK_AF4D5118D0F99DE FOREIGN KEY (unidade_ensino_id) REFERENCES edu_unidade_ensino (id)');
        $this->addSql('ALTER TABLE edu_turma ADD CONSTRAINT FK_AF4D511C5EE35FA FOREIGN KEY (etapa_id) REFERENCES edu_etapa (id)');
        $this->addSql('ALTER TABLE edu_turma ADD CONSTRAINT FK_AF4D51169C5211E FOREIGN KEY (turno_id) REFERENCES edu_turno (id)');
        $this->addSql('ALTER TABLE edu_turma ADD CONSTRAINT FK_AF4D511A7F6EA19 FOREIGN KEY (calendario_id) REFERENCES edu_calendario (id)');
        $this->addSql('ALTER TABLE edu_turma ADD CONSTRAINT FK_AF4D511F304037D FOREIGN KEY (calendario_periodo_id) REFERENCES edu_calendario_periodo (id)');
        $this->addSql('ALTER TABLE edu_turma ADD CONSTRAINT FK_AF4D511208D8E23 FOREIGN KEY (quadro_horario_id) REFERENCES edu_quadro_horario (id)');
        $this->addSql('ALTER TABLE edu_turma ADD CONSTRAINT FK_AF4D511E6EF7188 FOREIGN KEY (turma_agrupamento_id) REFERENCES edu_turma_agrupamento (id)');
        $this->addSql('ALTER TABLE edu_turma ADD CONSTRAINT FK_AF4D511AA7B4B22 FOREIGN KEY (disciplina_agrupamento_id) REFERENCES edu_disciplina_agrupamento (id)');
        $this->addSql('ALTER TABLE edu_sistema_avaliacao ADD CONSTRAINT FK_2E72CC6035E7D534 FOREIGN KEY (regime_id) REFERENCES edu_regime (id)');
        $this->addSql('ALTER TABLE edu_unidade_ensino_curso ADD CONSTRAINT FK_ACE4E9698D0F99DE FOREIGN KEY (unidade_ensino_id) REFERENCES edu_unidade_ensino (id)');
        $this->addSql('ALTER TABLE edu_unidade_ensino_curso ADD CONSTRAINT FK_ACE4E96987CB4A1F FOREIGN KEY (curso_id) REFERENCES edu_curso (id)');
        $this->addSql('ALTER TABLE edu_disciplina ADD CONSTRAINT FK_D179B51DC5EE35FA FOREIGN KEY (etapa_id) REFERENCES edu_etapa (id)');
        $this->addSql('ALTER TABLE edu_disciplina ADD CONSTRAINT FK_D179B51D87CB4A1F FOREIGN KEY (curso_id) REFERENCES edu_curso (id)');
        $this->addSql('ALTER TABLE edu_disciplina ADD CONSTRAINT FK_D179B51DAA7B4B22 FOREIGN KEY (disciplina_agrupamento_id) REFERENCES edu_disciplina_agrupamento (id)');
        $this->addSql('ALTER TABLE edu_etapa ADD CONSTRAINT FK_EC47D73C07F55F5 FOREIGN KEY (modulo_id) REFERENCES edu_modulo (id)');
        $this->addSql('ALTER TABLE edu_etapa ADD CONSTRAINT FK_EC47D7387CB4A1F FOREIGN KEY (curso_id) REFERENCES edu_curso (id)');
        $this->addSql('ALTER TABLE edu_etapa ADD CONSTRAINT FK_EC47D732F0688B4 FOREIGN KEY (quadro_horario_modelo_id) REFERENCES edu_quadro_horario_modelo (id)');
        $this->addSql('ALTER TABLE edu_etapa ADD CONSTRAINT FK_EC47D733F2340FB FOREIGN KEY (sistema_avaliacao_id) REFERENCES edu_sistema_avaliacao (id)');
        $this->addSql('ALTER TABLE edu_disciplina_agrupamento ADD CONSTRAINT FK_8E787AB7C5EE35FA FOREIGN KEY (etapa_id) REFERENCES edu_etapa (id)');
        $this->addSql('ALTER TABLE edu_curso ADD CONSTRAINT FK_EBCD8C5BB05E5EEA FOREIGN KEY (instituicao_id) REFERENCES edu_instituicao (id)');
        $this->addSql('ALTER TABLE edu_curso ADD CONSTRAINT FK_EBCD8C5BF5E98D2B FOREIGN KEY (modalidade_ensino_id) REFERENCES edu_modalidade_ensino (id)');
        $this->addSql('ALTER TABLE edu_turma_agrupamento ADD CONSTRAINT FK_5E0FFC5B8D0F99DE FOREIGN KEY (unidade_ensino_id) REFERENCES edu_unidade_ensino (id)');
        $this->addSql('ALTER TABLE edu_modulo ADD CONSTRAINT FK_B9D51FD587CB4A1F FOREIGN KEY (curso_id) REFERENCES edu_curso (id)');
        $this->addSql('ALTER TABLE edu_quadro_horario_modelo ADD CONSTRAINT FK_A1D49A5387CB4A1F FOREIGN KEY (curso_id) REFERENCES edu_curso (id)');
        $this->addSql('ALTER TABLE edu_calendario_periodo ADD CONSTRAINT FK_6F094727A7F6EA19 FOREIGN KEY (calendario_id) REFERENCES edu_calendario (id)');
        $this->addSql('ALTER TABLE edu_calendario ADD CONSTRAINT FK_8CB334B7B05E5EEA FOREIGN KEY (instituicao_id) REFERENCES edu_instituicao (id)');
        $this->addSql('ALTER TABLE edu_calendario ADD CONSTRAINT FK_8CB334B73B5FC2BB FOREIGN KEY (calendario_base_id) REFERENCES edu_calendario (id)');
        $this->addSql('ALTER TABLE edu_calendario_evento_dia ADD CONSTRAINT FK_CC0A03EEAC1F7597 FOREIGN KEY (dia_id) REFERENCES edu_calendario_dia (id)');
        $this->addSql('ALTER TABLE edu_calendario_evento_dia ADD CONSTRAINT FK_CC0A03EE87A5F842 FOREIGN KEY (evento_id) REFERENCES edu_calendario_evento (id)');
        $this->addSql('ALTER TABLE edu_calendario_dia ADD CONSTRAINT FK_FB5F2B2BA7F6EA19 FOREIGN KEY (calendario_id) REFERENCES edu_calendario (id)');
        $this->addSql('ALTER TABLE edu_quadro_horario ADD CONSTRAINT FK_1AFC7185C3A9576E FOREIGN KEY (modelo_id) REFERENCES edu_quadro_horario_modelo (id)');
        $this->addSql('ALTER TABLE edu_quadro_horario ADD CONSTRAINT FK_1AFC71858D0F99DE FOREIGN KEY (unidade_ensino_id) REFERENCES edu_unidade_ensino (id)');
        $this->addSql('ALTER TABLE edu_quadro_horario ADD CONSTRAINT FK_1AFC718569C5211E FOREIGN KEY (turno_id) REFERENCES edu_turno (id)');
        $this->addSql('ALTER TABLE edu_quadro_horario_dia_semana ADD CONSTRAINT FK_7EA346EA208D8E23 FOREIGN KEY (quadro_horario_id) REFERENCES edu_quadro_horario (id)');
        $this->addSql('ALTER TABLE edu_quadro_horario_aula_turma ADD CONSTRAINT FK_3C29BDF049A116CA FOREIGN KEY (turma_disciplina_id) REFERENCES edu_turma_disciplina (id)');
        $this->addSql('ALTER TABLE edu_quadro_horario_aula_turma ADD CONSTRAINT FK_3C29BDF08C9146E1 FOREIGN KEY (quadro_horario_aula_id) REFERENCES edu_quadro_horario_aula (id)');
        $this->addSql('ALTER TABLE edu_quadro_horario_aula ADD CONSTRAINT FK_F84A68CBA6EBF416 FOREIGN KEY (quadro_horario_dia_semana_id) REFERENCES edu_quadro_horario_dia_semana (id)');
        $this->addSql('ALTER TABLE edu_quadro_horario_aula ADD CONSTRAINT FK_F84A68CB208D8E23 FOREIGN KEY (quadro_horario_id) REFERENCES edu_quadro_horario (id)');
        $this->addSql('ALTER TABLE edu_avaliacao ADD CONSTRAINT FK_7F84084049A116CA FOREIGN KEY (turma_disciplina_id) REFERENCES edu_turma_disciplina (id)');
        $this->addSql('ALTER TABLE edu_avaliacao_qualitativa ADD CONSTRAINT FK_56BA43E2BF396750 FOREIGN KEY (id) REFERENCES edu_avaliacao (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE edu_avaliacao_habilidade ADD CONSTRAINT FK_24534CD32A30B056 FOREIGN KEY (disciplina_id) REFERENCES edu_disciplina (id)');
        $this->addSql('ALTER TABLE edu_avaliacao_quantitativa ADD CONSTRAINT FK_22351265A9276E6C FOREIGN KEY (tipo_id) REFERENCES edu_avaliacao_tipo (id)');
        $this->addSql('ALTER TABLE edu_avaliacao_quantitativa ADD CONSTRAINT FK_22351265BF396750 FOREIGN KEY (id) REFERENCES edu_avaliacao (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE edu_aula ADD CONSTRAINT FK_41219290CEBA2CFD FOREIGN KEY (turma_id) REFERENCES edu_turma (id)');
        $this->addSql('ALTER TABLE edu_aula ADD CONSTRAINT FK_41219290AC1F7597 FOREIGN KEY (dia_id) REFERENCES edu_calendario_dia (id)');
        $this->addSql('ALTER TABLE edu_aula ADD CONSTRAINT FK_412192908C9146E1 FOREIGN KEY (quadro_horario_aula_id) REFERENCES edu_quadro_horario_aula (id)');
        $this->addSql('ALTER TABLE edu_aula_turma_disciplina ADD CONSTRAINT FK_8DEF7428AD1A1255 FOREIGN KEY (aula_id) REFERENCES edu_aula (id)');
        $this->addSql('ALTER TABLE edu_aula_turma_disciplina ADD CONSTRAINT FK_8DEF742849A116CA FOREIGN KEY (turma_disciplina_id) REFERENCES edu_turma_disciplina (id)');
        $this->addSql('ALTER TABLE edu_aula_anotacao ADD CONSTRAINT FK_1BC42F77AD1A1255 FOREIGN KEY (aula_id) REFERENCES edu_aula (id)');
        $this->addSql('ALTER TABLE edu_aula_frequencia ADD CONSTRAINT FK_29529F1FAD1A1255 FOREIGN KEY (aula_id) REFERENCES edu_aula (id)');
        $this->addSql('ALTER TABLE edu_aula_frequencia_matricula_disciplina ADD CONSTRAINT FK_1E91CAE9A87573C7 FOREIGN KEY (frequencia_id) REFERENCES edu_aula_frequencia (id)');
        $this->addSql('ALTER TABLE edu_aula_frequencia_matricula_disciplina ADD CONSTRAINT FK_1E91CAE99D3DC654 FOREIGN KEY (matricula_disciplina_id) REFERENCES edu_matricula_disciplina (id)');
        $this->addSql('ALTER TABLE edu_nota ADD CONSTRAINT FK_8AE83C39EA9FDD75 FOREIGN KEY (media_id) REFERENCES edu_media (id)');
        $this->addSql('ALTER TABLE edu_nota_quantitativa ADD CONSTRAINT FK_A4D02A50813F7652 FOREIGN KEY (avaliacao_quantitativa_id) REFERENCES edu_avaliacao_quantitativa (id)');
        $this->addSql('ALTER TABLE edu_nota_quantitativa ADD CONSTRAINT FK_A4D02A50BF396750 FOREIGN KEY (id) REFERENCES edu_nota (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE edu_nota_qualitativa ADD CONSTRAINT FK_6050A232116A2E6D FOREIGN KEY (avaliacao_qualitativa_id) REFERENCES edu_avaliacao_qualitativa (id)');
        $this->addSql('ALTER TABLE edu_nota_qualitativa ADD CONSTRAINT FK_6050A232BF396750 FOREIGN KEY (id) REFERENCES edu_nota (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE edu_matricula_historico_observacao ADD CONSTRAINT FK_E22C9FC115C84B52 FOREIGN KEY (matricula_id) REFERENCES edu_matricula (id)');
        $this->addSql('ALTER TABLE edu_movimentacao ADD CONSTRAINT FK_9DBDF42D15C84B52 FOREIGN KEY (matricula_id) REFERENCES edu_matricula (id)');
        $this->addSql('ALTER TABLE edu_movimentacao_turma ADD CONSTRAINT FK_BD6FA8ABBD47951F FOREIGN KEY (enturmacao_origem_id) REFERENCES edu_enturmacao (id)');
        $this->addSql('ALTER TABLE edu_movimentacao_turma ADD CONSTRAINT FK_BD6FA8ABCB65DA36 FOREIGN KEY (enturmacao_destino_id) REFERENCES edu_enturmacao (id)');
        $this->addSql('ALTER TABLE edu_movimentacao_turma ADD CONSTRAINT FK_BD6FA8ABBF396750 FOREIGN KEY (id) REFERENCES edu_movimentacao (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE edu_movimentacao_transferencia ADD CONSTRAINT FK_1AE9B8C1215A5E9 FOREIGN KEY (unidade_ensino_origem_id) REFERENCES edu_unidade_ensino (id)');
        $this->addSql('ALTER TABLE edu_movimentacao_transferencia ADD CONSTRAINT FK_1AE9B8C19F04DF2F FOREIGN KEY (unidade_ensino_destino_id) REFERENCES edu_unidade_ensino (id)');
        $this->addSql('ALTER TABLE edu_movimentacao_transferencia ADD CONSTRAINT FK_1AE9B8C1BF396750 FOREIGN KEY (id) REFERENCES edu_movimentacao (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE edu_enturmacao ADD CONSTRAINT FK_3AADDEAF15C84B52 FOREIGN KEY (matricula_id) REFERENCES edu_matricula (id)');
        $this->addSql('ALTER TABLE edu_enturmacao ADD CONSTRAINT FK_3AADDEAFCEBA2CFD FOREIGN KEY (turma_id) REFERENCES edu_turma (id)');
        $this->addSql('ALTER TABLE edu_movimentacao_reclassificacao_nota ADD CONSTRAINT FK_EC786B85DAE4A065 FOREIGN KEY (reclassificacao_id) REFERENCES edu_movimentacao_reclassificacao (id)');
        $this->addSql('ALTER TABLE edu_movimentacao_reclassificacao_nota ADD CONSTRAINT FK_EC786B852A30B056 FOREIGN KEY (disciplina_id) REFERENCES edu_disciplina (id)');
        $this->addSql('ALTER TABLE edu_media ADD CONSTRAINT FK_4BDA6DBB9D3DC654 FOREIGN KEY (matricula_disciplina_id) REFERENCES edu_matricula_disciplina (id)');
        $this->addSql('ALTER TABLE edu_movimentacao_retorno ADD CONSTRAINT FK_A97BCC2B8D0F99DE FOREIGN KEY (unidade_ensino_id) REFERENCES edu_unidade_ensino (id)');
        $this->addSql('ALTER TABLE edu_movimentacao_retorno ADD CONSTRAINT FK_A97BCC2BC5EE35FA FOREIGN KEY (etapa_id) REFERENCES edu_etapa (id)');
        $this->addSql('ALTER TABLE edu_movimentacao_retorno ADD CONSTRAINT FK_A97BCC2BBF396750 FOREIGN KEY (id) REFERENCES edu_movimentacao (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE edu_nota_qualitativa_habilidade ADD CONSTRAINT FK_D0170E4BFDD1D822 FOREIGN KEY (habilidade_id) REFERENCES edu_avaliacao_habilidade (id)');
        $this->addSql('ALTER TABLE edu_nota_qualitativa_habilidade ADD CONSTRAINT FK_D0170E4B48FA63EE FOREIGN KEY (conceito_id) REFERENCES edu_avaliacao_conceito (id)');
        $this->addSql('ALTER TABLE edu_nota_qualitativa_habilidade ADD CONSTRAINT FK_D0170E4B90636C03 FOREIGN KEY (nota_qualitativa_id) REFERENCES edu_nota_qualitativa (id)');
        $this->addSql('ALTER TABLE edu_uniforme ADD CONSTRAINT FK_49A957D315C84B52 FOREIGN KEY (matricula_id) REFERENCES edu_matricula (id)');
        $this->addSql('ALTER TABLE edu_movimentacao_desligamento ADD CONSTRAINT FK_64B3CC05BF396750 FOREIGN KEY (id) REFERENCES edu_movimentacao (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE edu_matricula_etapa ADD CONSTRAINT FK_BD2A83DD15C84B52 FOREIGN KEY (matricula_id) REFERENCES edu_matricula (id)');
        $this->addSql('ALTER TABLE edu_matricula_etapa ADD CONSTRAINT FK_BD2A83DDC5EE35FA FOREIGN KEY (etapa_id) REFERENCES edu_etapa (id)');
        $this->addSql('ALTER TABLE edu_matricula_etapa ADD CONSTRAINT FK_BD2A83DD9586CC8 FOREIGN KEY (cidade_id) REFERENCES sme_cidade (id)');
        $this->addSql('ALTER TABLE edu_matricula_etapa ADD CONSTRAINT FK_BD2A83DDEB5D3E62 FOREIGN KEY (enturmacao_id) REFERENCES edu_enturmacao (id)');
        $this->addSql('ALTER TABLE edu_matricula_disciplina ADD CONSTRAINT FK_1443F5AF15C84B52 FOREIGN KEY (matricula_id) REFERENCES edu_matricula (id)');
        $this->addSql('ALTER TABLE edu_matricula_disciplina ADD CONSTRAINT FK_1443F5AF2A30B056 FOREIGN KEY (disciplina_id) REFERENCES edu_disciplina (id)');
        $this->addSql('ALTER TABLE edu_matricula_disciplina ADD CONSTRAINT FK_1443F5AFEB5D3E62 FOREIGN KEY (enturmacao_id) REFERENCES edu_enturmacao (id)');
        $this->addSql('ALTER TABLE edu_matricula_disciplina ADD CONSTRAINT FK_1443F5AF49A116CA FOREIGN KEY (turma_disciplina_id) REFERENCES edu_turma_disciplina (id)');
        $this->addSql('ALTER TABLE edu_matricula ADD CONSTRAINT FK_34057E7C83F5509 FOREIGN KEY (pessoa_fisica_aluno_id) REFERENCES sme_pessoa_fisica (id)');
        $this->addSql('ALTER TABLE edu_matricula ADD CONSTRAINT FK_34057E787CB4A1F FOREIGN KEY (curso_id) REFERENCES edu_curso (id)');
        $this->addSql('ALTER TABLE edu_matricula ADD CONSTRAINT FK_34057E7C5EE35FA FOREIGN KEY (etapa_id) REFERENCES edu_etapa (id)');
        $this->addSql('ALTER TABLE edu_matricula ADD CONSTRAINT FK_34057E78D0F99DE FOREIGN KEY (unidade_ensino_id) REFERENCES edu_unidade_ensino (id)');
        $this->addSql('ALTER TABLE edu_movimentacao_reclassificacao ADD CONSTRAINT FK_79406D86BD47951F FOREIGN KEY (enturmacao_origem_id) REFERENCES edu_enturmacao (id)');
        $this->addSql('ALTER TABLE edu_movimentacao_reclassificacao ADD CONSTRAINT FK_79406D86CB65DA36 FOREIGN KEY (enturmacao_destino_id) REFERENCES edu_enturmacao (id)');
        $this->addSql('ALTER TABLE edu_movimentacao_reclassificacao ADD CONSTRAINT FK_79406D86BF396750 FOREIGN KEY (id) REFERENCES edu_movimentacao (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE edu_vinculo ADD CONSTRAINT FK_4D9790F7E2D44972 FOREIGN KEY (pessoa_fisica_funcionario_id) REFERENCES sme_pessoa_fisica (id)');
        $this->addSql('ALTER TABLE edu_vinculo ADD CONSTRAINT FK_4D9790F7813AC380 FOREIGN KEY (cargo_id) REFERENCES edu_cargo (id)');
        $this->addSql('ALTER TABLE edu_vinculo ADD CONSTRAINT FK_4D9790F7B05E5EEA FOREIGN KEY (instituicao_id) REFERENCES edu_instituicao (id)');
        $this->addSql('ALTER TABLE edu_cargo ADD CONSTRAINT FK_1A189BC68FC40795 FOREIGN KEY (acesso_grupo_id) REFERENCES edu_acesso_grupo (id)');
        $this->addSql('ALTER TABLE edu_alocacao ADD CONSTRAINT FK_89250D206A4AB3EE FOREIGN KEY (vinculo_id) REFERENCES edu_vinculo (id)');
        $this->addSql('ALTER TABLE edu_alocacao ADD CONSTRAINT FK_89250D20B05E5EEA FOREIGN KEY (instituicao_id) REFERENCES edu_instituicao (id)');
        $this->addSql('ALTER TABLE edu_vaga ADD CONSTRAINT FK_74342FD1CEBA2CFD FOREIGN KEY (turma_id) REFERENCES edu_turma (id)');
        $this->addSql('ALTER TABLE edu_vaga ADD CONSTRAINT FK_74342FD1EB5D3E62 FOREIGN KEY (enturmacao_id) REFERENCES edu_enturmacao (id)');
    }

    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE edu_acesso_atribuicao DROP FOREIGN KEY FK_E55ADF3D9C833003');
        $this->addSql('ALTER TABLE edu_acesso_permissao_grupo DROP FOREIGN KEY FK_ED3904479C833003');
        $this->addSql('ALTER TABLE edu_cargo DROP FOREIGN KEY FK_1A189BC68FC40795');
        $this->addSql('ALTER TABLE edu_acesso_permissao_grupo DROP FOREIGN KEY FK_ED390447E009E574');
        $this->addSql('ALTER TABLE edu_acesso_atribuicao DROP FOREIGN KEY FK_E55ADF3DDB38439E');
        $this->addSql('ALTER TABLE sme_pessoa DROP FOREIGN KEY FK_B3530DBEDB38439E');
        $this->addSql('ALTER TABLE sme_pessoa_juridica DROP FOREIGN KEY FK_74B6057EBF396750');
        $this->addSql('ALTER TABLE edu_instituicao DROP FOREIGN KEY FK_CD57CCD2BF396750');
        $this->addSql('ALTER TABLE edu_unidade_ensino DROP FOREIGN KEY FK_C03EFDE1BF396750');
        $this->addSql('ALTER TABLE sme_pessoa_telefone DROP FOREIGN KEY FK_9A323A2EDF6FA0A5');
        $this->addSql('ALTER TABLE sme_pessoa_fisica DROP FOREIGN KEY FK_F4375A60BF396750');
        $this->addSql('ALTER TABLE sme_pessoa_fisica_particularidade DROP FOREIGN KEY FK_96A1CA5E938C9B05');
        $this->addSql('ALTER TABLE sme_pessoa_fisica DROP FOREIGN KEY FK_F4375A60E13B435A');
        $this->addSql('ALTER TABLE edu_acesso_atribuicao DROP FOREIGN KEY FK_E55ADF3DB05E5EEA');
        $this->addSql('ALTER TABLE edu_instituicao DROP FOREIGN KEY FK_CD57CCD222EAC624');
        $this->addSql('ALTER TABLE edu_curso DROP FOREIGN KEY FK_EBCD8C5BB05E5EEA');
        $this->addSql('ALTER TABLE edu_calendario DROP FOREIGN KEY FK_8CB334B7B05E5EEA');
        $this->addSql('ALTER TABLE edu_vinculo DROP FOREIGN KEY FK_4D9790F7B05E5EEA');
        $this->addSql('ALTER TABLE edu_alocacao DROP FOREIGN KEY FK_89250D20B05E5EEA');
        $this->addSql('ALTER TABLE edu_turma DROP FOREIGN KEY FK_AF4D5118D0F99DE');
        $this->addSql('ALTER TABLE edu_unidade_ensino_curso DROP FOREIGN KEY FK_ACE4E9698D0F99DE');
        $this->addSql('ALTER TABLE edu_turma_agrupamento DROP FOREIGN KEY FK_5E0FFC5B8D0F99DE');
        $this->addSql('ALTER TABLE edu_quadro_horario DROP FOREIGN KEY FK_1AFC71858D0F99DE');
        $this->addSql('ALTER TABLE edu_movimentacao_transferencia DROP FOREIGN KEY FK_1AE9B8C1215A5E9');
        $this->addSql('ALTER TABLE edu_movimentacao_transferencia DROP FOREIGN KEY FK_1AE9B8C19F04DF2F');
        $this->addSql('ALTER TABLE edu_movimentacao_retorno DROP FOREIGN KEY FK_A97BCC2B8D0F99DE');
        $this->addSql('ALTER TABLE edu_matricula DROP FOREIGN KEY FK_34057E78D0F99DE');
        $this->addSql('ALTER TABLE edu_unidade_ensino DROP FOREIGN KEY FK_C03EFDE1A9276E6C');
        $this->addSql('ALTER TABLE sme_pessoa_fisica_necessidade_especial DROP FOREIGN KEY FK_24240AD9349DA9B6');
        $this->addSql('ALTER TABLE sme_pessoa_fisica DROP FOREIGN KEY FK_F4375A60ABDA9359');
        $this->addSql('ALTER TABLE sme_cidade DROP FOREIGN KEY FK_C51495609F5A440B');
        $this->addSql('ALTER TABLE sme_pessoa_fisica DROP FOREIGN KEY FK_F4375A6075376D93');
        $this->addSql('ALTER TABLE edu_pessoa_fisica_beneficio_social DROP FOREIGN KEY FK_354784D86184F2DF');
        $this->addSql('ALTER TABLE sme_pessoa_fisica_particularidade DROP FOREIGN KEY FK_96A1CA5E8679B4F7');
        $this->addSql('ALTER TABLE sme_pessoa_fisica_necessidade_especial DROP FOREIGN KEY FK_24240AD98679B4F7');
        $this->addSql('ALTER TABLE edu_pessoa_fisica_beneficio_social DROP FOREIGN KEY FK_354784D88679B4F7');
        $this->addSql('ALTER TABLE edu_matricula DROP FOREIGN KEY FK_34057E7C83F5509');
        $this->addSql('ALTER TABLE edu_vinculo DROP FOREIGN KEY FK_4D9790F7E2D44972');
        $this->addSql('ALTER TABLE sme_pessoa_fisica DROP FOREIGN KEY FK_F4375A60737AA82E');
        $this->addSql('ALTER TABLE sme_endereco DROP FOREIGN KEY FK_B4A606A09586CC8');
        $this->addSql('ALTER TABLE edu_matricula_etapa DROP FOREIGN KEY FK_BD2A83DD9586CC8');
        $this->addSql('ALTER TABLE sme_estado DROP FOREIGN KEY FK_89D147DFC604D5C6');
        $this->addSql('ALTER TABLE sme_pessoa_fisica DROP FOREIGN KEY FK_F4375A60F46BFC5F');
        $this->addSql('ALTER TABLE sme_pessoa DROP FOREIGN KEY FK_B3530DBE1BB76823');
        $this->addSql('ALTER TABLE edu_turma_disciplina_alocacao DROP FOREIGN KEY FK_4C721EF749A116CA');
        $this->addSql('ALTER TABLE edu_quadro_horario_aula_turma DROP FOREIGN KEY FK_3C29BDF049A116CA');
        $this->addSql('ALTER TABLE edu_avaliacao DROP FOREIGN KEY FK_7F84084049A116CA');
        $this->addSql('ALTER TABLE edu_aula_turma_disciplina DROP FOREIGN KEY FK_8DEF742849A116CA');
        $this->addSql('ALTER TABLE edu_matricula_disciplina DROP FOREIGN KEY FK_1443F5AF49A116CA');
        $this->addSql('ALTER TABLE edu_turma_disciplina DROP FOREIGN KEY FK_9D020B06CEBA2CFD');
        $this->addSql('ALTER TABLE edu_aula DROP FOREIGN KEY FK_41219290CEBA2CFD');
        $this->addSql('ALTER TABLE edu_enturmacao DROP FOREIGN KEY FK_3AADDEAFCEBA2CFD');
        $this->addSql('ALTER TABLE edu_vaga DROP FOREIGN KEY FK_74342FD1CEBA2CFD');
        $this->addSql('ALTER TABLE edu_etapa DROP FOREIGN KEY FK_EC47D733F2340FB');
        $this->addSql('ALTER TABLE edu_sistema_avaliacao DROP FOREIGN KEY FK_2E72CC6035E7D534');
        $this->addSql('ALTER TABLE edu_turma DROP FOREIGN KEY FK_AF4D51169C5211E');
        $this->addSql('ALTER TABLE edu_quadro_horario DROP FOREIGN KEY FK_1AFC718569C5211E');
        $this->addSql('ALTER TABLE edu_curso DROP FOREIGN KEY FK_EBCD8C5BF5E98D2B');
        $this->addSql('ALTER TABLE edu_turma_disciplina DROP FOREIGN KEY FK_9D020B062A30B056');
        $this->addSql('ALTER TABLE edu_avaliacao_habilidade DROP FOREIGN KEY FK_24534CD32A30B056');
        $this->addSql('ALTER TABLE edu_movimentacao_reclassificacao_nota DROP FOREIGN KEY FK_EC786B852A30B056');
        $this->addSql('ALTER TABLE edu_matricula_disciplina DROP FOREIGN KEY FK_1443F5AF2A30B056');
        $this->addSql('ALTER TABLE edu_turma DROP FOREIGN KEY FK_AF4D511C5EE35FA');
        $this->addSql('ALTER TABLE edu_disciplina DROP FOREIGN KEY FK_D179B51DC5EE35FA');
        $this->addSql('ALTER TABLE edu_disciplina_agrupamento DROP FOREIGN KEY FK_8E787AB7C5EE35FA');
        $this->addSql('ALTER TABLE edu_movimentacao_retorno DROP FOREIGN KEY FK_A97BCC2BC5EE35FA');
        $this->addSql('ALTER TABLE edu_matricula_etapa DROP FOREIGN KEY FK_BD2A83DDC5EE35FA');
        $this->addSql('ALTER TABLE edu_matricula DROP FOREIGN KEY FK_34057E7C5EE35FA');
        $this->addSql('ALTER TABLE edu_turma DROP FOREIGN KEY FK_AF4D511AA7B4B22');
        $this->addSql('ALTER TABLE edu_disciplina DROP FOREIGN KEY FK_D179B51DAA7B4B22');
        $this->addSql('ALTER TABLE edu_unidade_ensino_curso DROP FOREIGN KEY FK_ACE4E96987CB4A1F');
        $this->addSql('ALTER TABLE edu_disciplina DROP FOREIGN KEY FK_D179B51D87CB4A1F');
        $this->addSql('ALTER TABLE edu_etapa DROP FOREIGN KEY FK_EC47D7387CB4A1F');
        $this->addSql('ALTER TABLE edu_modulo DROP FOREIGN KEY FK_B9D51FD587CB4A1F');
        $this->addSql('ALTER TABLE edu_quadro_horario_modelo DROP FOREIGN KEY FK_A1D49A5387CB4A1F');
        $this->addSql('ALTER TABLE edu_matricula DROP FOREIGN KEY FK_34057E787CB4A1F');
        $this->addSql('ALTER TABLE edu_turma DROP FOREIGN KEY FK_AF4D511E6EF7188');
        $this->addSql('ALTER TABLE edu_etapa DROP FOREIGN KEY FK_EC47D73C07F55F5');
        $this->addSql('ALTER TABLE edu_etapa DROP FOREIGN KEY FK_EC47D732F0688B4');
        $this->addSql('ALTER TABLE edu_quadro_horario DROP FOREIGN KEY FK_1AFC7185C3A9576E');
        $this->addSql('ALTER TABLE edu_turma DROP FOREIGN KEY FK_AF4D511F304037D');
        $this->addSql('ALTER TABLE edu_turma DROP FOREIGN KEY FK_AF4D511A7F6EA19');
        $this->addSql('ALTER TABLE edu_calendario_periodo DROP FOREIGN KEY FK_6F094727A7F6EA19');
        $this->addSql('ALTER TABLE edu_calendario DROP FOREIGN KEY FK_8CB334B73B5FC2BB');
        $this->addSql('ALTER TABLE edu_calendario_dia DROP FOREIGN KEY FK_FB5F2B2BA7F6EA19');
        $this->addSql('ALTER TABLE edu_calendario_evento_dia DROP FOREIGN KEY FK_CC0A03EE87A5F842');
        $this->addSql('ALTER TABLE edu_calendario_evento_dia DROP FOREIGN KEY FK_CC0A03EEAC1F7597');
        $this->addSql('ALTER TABLE edu_aula DROP FOREIGN KEY FK_41219290AC1F7597');
        $this->addSql('ALTER TABLE edu_turma DROP FOREIGN KEY FK_AF4D511208D8E23');
        $this->addSql('ALTER TABLE edu_quadro_horario_dia_semana DROP FOREIGN KEY FK_7EA346EA208D8E23');
        $this->addSql('ALTER TABLE edu_quadro_horario_aula DROP FOREIGN KEY FK_F84A68CB208D8E23');
        $this->addSql('ALTER TABLE edu_quadro_horario_aula DROP FOREIGN KEY FK_F84A68CBA6EBF416');
        $this->addSql('ALTER TABLE edu_quadro_horario_aula_turma DROP FOREIGN KEY FK_3C29BDF08C9146E1');
        $this->addSql('ALTER TABLE edu_aula DROP FOREIGN KEY FK_412192908C9146E1');
        $this->addSql('ALTER TABLE edu_avaliacao_quantitativa DROP FOREIGN KEY FK_22351265A9276E6C');
        $this->addSql('ALTER TABLE edu_avaliacao_qualitativa DROP FOREIGN KEY FK_56BA43E2BF396750');
        $this->addSql('ALTER TABLE edu_avaliacao_quantitativa DROP FOREIGN KEY FK_22351265BF396750');
        $this->addSql('ALTER TABLE edu_nota_qualitativa DROP FOREIGN KEY FK_6050A232116A2E6D');
        $this->addSql('ALTER TABLE edu_nota_qualitativa_habilidade DROP FOREIGN KEY FK_D0170E4BFDD1D822');
        $this->addSql('ALTER TABLE edu_nota_qualitativa_habilidade DROP FOREIGN KEY FK_D0170E4B48FA63EE');
        $this->addSql('ALTER TABLE edu_nota_quantitativa DROP FOREIGN KEY FK_A4D02A50813F7652');
        $this->addSql('ALTER TABLE edu_aula_turma_disciplina DROP FOREIGN KEY FK_8DEF7428AD1A1255');
        $this->addSql('ALTER TABLE edu_aula_anotacao DROP FOREIGN KEY FK_1BC42F77AD1A1255');
        $this->addSql('ALTER TABLE edu_aula_frequencia DROP FOREIGN KEY FK_29529F1FAD1A1255');
        $this->addSql('ALTER TABLE edu_aula_frequencia_matricula_disciplina DROP FOREIGN KEY FK_1E91CAE9A87573C7');
        $this->addSql('ALTER TABLE edu_nota_quantitativa DROP FOREIGN KEY FK_A4D02A50BF396750');
        $this->addSql('ALTER TABLE edu_nota_qualitativa DROP FOREIGN KEY FK_6050A232BF396750');
        $this->addSql('ALTER TABLE edu_nota_qualitativa_habilidade DROP FOREIGN KEY FK_D0170E4B90636C03');
        $this->addSql('ALTER TABLE edu_movimentacao_turma DROP FOREIGN KEY FK_BD6FA8ABBF396750');
        $this->addSql('ALTER TABLE edu_movimentacao_transferencia DROP FOREIGN KEY FK_1AE9B8C1BF396750');
        $this->addSql('ALTER TABLE edu_movimentacao_retorno DROP FOREIGN KEY FK_A97BCC2BBF396750');
        $this->addSql('ALTER TABLE edu_movimentacao_desligamento DROP FOREIGN KEY FK_64B3CC05BF396750');
        $this->addSql('ALTER TABLE edu_movimentacao_reclassificacao DROP FOREIGN KEY FK_79406D86BF396750');
        $this->addSql('ALTER TABLE edu_movimentacao_turma DROP FOREIGN KEY FK_BD6FA8ABBD47951F');
        $this->addSql('ALTER TABLE edu_movimentacao_turma DROP FOREIGN KEY FK_BD6FA8ABCB65DA36');
        $this->addSql('ALTER TABLE edu_matricula_etapa DROP FOREIGN KEY FK_BD2A83DDEB5D3E62');
        $this->addSql('ALTER TABLE edu_matricula_disciplina DROP FOREIGN KEY FK_1443F5AFEB5D3E62');
        $this->addSql('ALTER TABLE edu_movimentacao_reclassificacao DROP FOREIGN KEY FK_79406D86BD47951F');
        $this->addSql('ALTER TABLE edu_movimentacao_reclassificacao DROP FOREIGN KEY FK_79406D86CB65DA36');
        $this->addSql('ALTER TABLE edu_vaga DROP FOREIGN KEY FK_74342FD1EB5D3E62');
        $this->addSql('ALTER TABLE edu_nota DROP FOREIGN KEY FK_8AE83C39EA9FDD75');
        $this->addSql('ALTER TABLE edu_aula_frequencia_matricula_disciplina DROP FOREIGN KEY FK_1E91CAE99D3DC654');
        $this->addSql('ALTER TABLE edu_media DROP FOREIGN KEY FK_4BDA6DBB9D3DC654');
        $this->addSql('ALTER TABLE edu_matricula_historico_observacao DROP FOREIGN KEY FK_E22C9FC115C84B52');
        $this->addSql('ALTER TABLE edu_movimentacao DROP FOREIGN KEY FK_9DBDF42D15C84B52');
        $this->addSql('ALTER TABLE edu_enturmacao DROP FOREIGN KEY FK_3AADDEAF15C84B52');
        $this->addSql('ALTER TABLE edu_uniforme DROP FOREIGN KEY FK_49A957D315C84B52');
        $this->addSql('ALTER TABLE edu_matricula_etapa DROP FOREIGN KEY FK_BD2A83DD15C84B52');
        $this->addSql('ALTER TABLE edu_matricula_disciplina DROP FOREIGN KEY FK_1443F5AF15C84B52');
        $this->addSql('ALTER TABLE edu_movimentacao_reclassificacao_nota DROP FOREIGN KEY FK_EC786B85DAE4A065');
        $this->addSql('ALTER TABLE edu_alocacao DROP FOREIGN KEY FK_89250D206A4AB3EE');
        $this->addSql('ALTER TABLE edu_vinculo DROP FOREIGN KEY FK_4D9790F7813AC380');
        $this->addSql('ALTER TABLE edu_turma_disciplina_alocacao DROP FOREIGN KEY FK_4C721EF7110E6AE8');
        $this->addSql('DROP TABLE edu_acesso_atribuicao');
        $this->addSql('DROP TABLE edu_acesso_grupo');
        $this->addSql('DROP TABLE edu_acesso_permissao');
        $this->addSql('DROP TABLE edu_acesso_permissao_grupo');
        $this->addSql('DROP TABLE edu_acesso_usuario');
        $this->addSql('DROP TABLE sme_pessoa');
        $this->addSql('DROP TABLE sme_particularidade');
        $this->addSql('DROP TABLE sme_raca');
        $this->addSql('DROP TABLE sme_pessoa_juridica');
        $this->addSql('DROP TABLE edu_instituicao');
        $this->addSql('DROP TABLE edu_unidade_ensino');
        $this->addSql('DROP TABLE edu_tipo_unidade_ensino');
        $this->addSql('DROP TABLE sme_necessidade_especial');
        $this->addSql('DROP TABLE sme_pessoa_telefone');
        $this->addSql('DROP TABLE sme_estado');
        $this->addSql('DROP TABLE sme_estado_civil');
        $this->addSql('DROP TABLE edu_beneficio_social');
        $this->addSql('DROP TABLE sme_pessoa_fisica');
        $this->addSql('DROP TABLE sme_pessoa_fisica_particularidade');
        $this->addSql('DROP TABLE sme_pessoa_fisica_necessidade_especial');
        $this->addSql('DROP TABLE edu_pessoa_fisica_beneficio_social');
        $this->addSql('DROP TABLE sme_cidade');
        $this->addSql('DROP TABLE sme_pais');
        $this->addSql('DROP TABLE sme_endereco');
        $this->addSql('DROP TABLE edu_turma_disciplina');
        $this->addSql('DROP TABLE edu_turma_disciplina_alocacao');
        $this->addSql('DROP TABLE edu_turma');
        $this->addSql('DROP TABLE edu_sistema_avaliacao');
        $this->addSql('DROP TABLE edu_unidade_ensino_curso');
        $this->addSql('DROP TABLE edu_regime');
        $this->addSql('DROP TABLE edu_turno');
        $this->addSql('DROP TABLE edu_modalidade_ensino');
        $this->addSql('DROP TABLE edu_disciplina');
        $this->addSql('DROP TABLE edu_etapa');
        $this->addSql('DROP TABLE edu_disciplina_agrupamento');
        $this->addSql('DROP TABLE edu_curso');
        $this->addSql('DROP TABLE edu_turma_agrupamento');
        $this->addSql('DROP TABLE edu_modulo');
        $this->addSql('DROP TABLE edu_quadro_horario_modelo');
        $this->addSql('DROP TABLE edu_calendario_periodo');
        $this->addSql('DROP TABLE edu_calendario');
        $this->addSql('DROP TABLE edu_calendario_evento_dia');
        $this->addSql('DROP TABLE edu_calendario_evento');
        $this->addSql('DROP TABLE edu_calendario_dia');
        $this->addSql('DROP TABLE edu_quadro_horario');
        $this->addSql('DROP TABLE edu_quadro_horario_dia_semana');
        $this->addSql('DROP TABLE edu_quadro_horario_aula_turma');
        $this->addSql('DROP TABLE edu_quadro_horario_aula');
        $this->addSql('DROP TABLE edu_avaliacao_tipo');
        $this->addSql('DROP TABLE edu_avaliacao');
        $this->addSql('DROP TABLE edu_avaliacao_qualitativa');
        $this->addSql('DROP TABLE edu_avaliacao_habilidade');
        $this->addSql('DROP TABLE edu_avaliacao_conceito');
        $this->addSql('DROP TABLE edu_avaliacao_quantitativa');
        $this->addSql('DROP TABLE edu_aula');
        $this->addSql('DROP TABLE edu_aula_turma_disciplina');
        $this->addSql('DROP TABLE edu_aula_anotacao');
        $this->addSql('DROP TABLE edu_aula_frequencia');
        $this->addSql('DROP TABLE edu_aula_frequencia_matricula_disciplina');
        $this->addSql('DROP TABLE edu_nota');
        $this->addSql('DROP TABLE edu_nota_quantitativa');
        $this->addSql('DROP TABLE edu_nota_qualitativa');
        $this->addSql('DROP TABLE edu_matricula_historico_observacao');
        $this->addSql('DROP TABLE edu_movimentacao');
        $this->addSql('DROP TABLE edu_movimentacao_turma');
        $this->addSql('DROP TABLE edu_movimentacao_transferencia');
        $this->addSql('DROP TABLE edu_enturmacao');
        $this->addSql('DROP TABLE edu_movimentacao_reclassificacao_nota');
        $this->addSql('DROP TABLE edu_media');
        $this->addSql('DROP TABLE edu_movimentacao_retorno');
        $this->addSql('DROP TABLE edu_nota_qualitativa_habilidade');
        $this->addSql('DROP TABLE edu_uniforme');
        $this->addSql('DROP TABLE edu_movimentacao_desligamento');
        $this->addSql('DROP TABLE edu_matricula_etapa');
        $this->addSql('DROP TABLE edu_matricula_disciplina');
        $this->addSql('DROP TABLE edu_matricula');
        $this->addSql('DROP TABLE edu_movimentacao_reclassificacao');
        $this->addSql('DROP TABLE edu_vinculo');
        $this->addSql('DROP TABLE edu_cargo');
        $this->addSql('DROP TABLE edu_alocacao');
        $this->addSql('DROP TABLE edu_vaga');
    }
}
