<?php

namespace SME\DGPFormacaoBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class MatriculaController__JMSInjector
{
    public static function inject($container) {
        $instance = new \SME\DGPFormacaoBundle\Controller\MatriculaController();
        return $instance;
    }
}
