<?php

namespace SME\DGPPromocaoBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PromocaoHorizontalController__JMSInjector
{
    public static function inject($container) {
        $instance = new \SME\DGPPromocaoBundle\Controller\PromocaoHorizontalController();
        return $instance;
    }
}
