<?php

namespace SME\DGPContratacaoBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ProcessoController__JMSInjector
{
    public static function inject($container) {
        $instance = new \SME\DGPContratacaoBundle\Controller\ProcessoController();
        return $instance;
    }
}
