<?php

namespace SME\DGPProcessoAnualBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ProcessoAnualController__JMSInjector
{
    public static function inject($container) {
        $instance = new \SME\DGPProcessoAnualBundle\Controller\ProcessoAnualController();
        return $instance;
    }
}
