<?php

namespace SME\EstagioBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class EstagioController__JMSInjector
{
    public static function inject($container) {
        $instance = new \SME\EstagioBundle\Controller\EstagioController();
        return $instance;
    }
}
