<?php

namespace SME\FilaUnicaBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class InscricaoController__JMSInjector
{
    public static function inject($container) {
        require_once '/var/www/html/intranet/app/cache/dev/jms_diextra/proxies/SME-FilaUnicaBundle-Controller-InscricaoController.php';
        $c = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('SME\\FilaUnicaBundle\\Controller\\InscricaoController' => array('reordenarGeralAction' => array(0 => 'security.access.method_interceptor'), 'redefinirAnosEscolaresAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy_a45e546e95050fd717643845b37cab00e4f09a48\__CG__\SME\FilaUnicaBundle\Controller\InscricaoController();
        $instance->__CGInterception__setLoader($c);
        return $instance;
    }
}
