<?php

namespace SME\IntranetBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class RoleController__JMSInjector
{
    public static function inject($container) {
        $instance = new \SME\IntranetBundle\Controller\RoleController();
        return $instance;
    }
}
