<?php

namespace SME\PublicBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PublicController__JMSInjector
{
    public static function inject($container) {
        $instance = new \SME\PublicBundle\Controller\PublicController();
        return $instance;
    }
}
