<?php

namespace SME\ProtocoloBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class EncaminhamentoController__JMSInjector
{
    public static function inject($container) {
        $instance = new \SME\ProtocoloBundle\Controller\EncaminhamentoController();
        return $instance;
    }
}
