<?php

namespace SME\PresencaBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PresencaController__JMSInjector
{
    public static function inject($container) {
        $instance = new \SME\PresencaBundle\Controller\PresencaController();
        return $instance;
    }
}
