<?php

namespace SME\QuestionarioBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class QuestionarioController__JMSInjector
{
    public static function inject($container) {
        $instance = new \SME\QuestionarioBundle\Controller\QuestionarioController();
        return $instance;
    }
}
