<?php

namespace SME\SuporteTecnicoBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class AtividadeController__JMSInjector
{
    public static function inject($container) {
        $instance = new \SME\SuporteTecnicoBundle\Controller\AtividadeController();
        return $instance;
    }
}
