<?php

namespace Proxies\__CG__\SME\ProtocoloBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Protocolo extends \SME\ProtocoloBundle\Entity\Protocolo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'solicitacao', 'requerente', 'responsavelAtual', 'situacao', 'dataCadastro', 'dataModificacao', 'dataEncerramento', 'observacao', 'ativo', 'encaminhamentos', 'informacoesDocumento');
        }

        return array('__isInitialized__', 'id', 'solicitacao', 'requerente', 'responsavelAtual', 'situacao', 'dataCadastro', 'dataModificacao', 'dataEncerramento', 'observacao', 'ativo', 'encaminhamentos', 'informacoesDocumento');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Protocolo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getProtocolo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProtocolo', array());

        return parent::getProtocolo();
    }

    /**
     * {@inheritDoc}
     */
    public function getSolicitacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSolicitacao', array());

        return parent::getSolicitacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setSolicitacao(\SME\ProtocoloBundle\Entity\Solicitacao $solicitacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSolicitacao', array($solicitacao));

        return parent::setSolicitacao($solicitacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequerente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequerente', array());

        return parent::getRequerente();
    }

    /**
     * {@inheritDoc}
     */
    public function setRequerente(\SME\CommonsBundle\Entity\PessoaFisica $requerente = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequerente', array($requerente));

        return parent::setRequerente($requerente);
    }

    /**
     * {@inheritDoc}
     */
    public function getResponsavelAtual()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResponsavelAtual', array());

        return parent::getResponsavelAtual();
    }

    /**
     * {@inheritDoc}
     */
    public function setResponsavelAtual(\SME\CommonsBundle\Entity\PessoaFisica $responsavelAtual)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResponsavelAtual', array($responsavelAtual));

        return parent::setResponsavelAtual($responsavelAtual);
    }

    /**
     * {@inheritDoc}
     */
    public function getSituacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSituacao', array());

        return parent::getSituacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setSituacao(\SME\ProtocoloBundle\Entity\Situacao $situacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSituacao', array($situacao));

        return parent::setSituacao($situacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataCadastro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataCadastro', array());

        return parent::getDataCadastro();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataCadastro(\DateTime $dataCadastro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataCadastro', array($dataCadastro));

        return parent::setDataCadastro($dataCadastro);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataModificacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataModificacao', array());

        return parent::getDataModificacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataModificacao(\DateTime $dataModificacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataModificacao', array($dataModificacao));

        return parent::setDataModificacao($dataModificacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataEncerramento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataEncerramento', array());

        return parent::getDataEncerramento();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataEncerramento(\DateTime $dataEncerramento = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataEncerramento', array($dataEncerramento));

        return parent::setDataEncerramento($dataEncerramento);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservacao', array());

        return parent::getObservacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservacao($observacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservacao', array($observacao));

        return parent::setObservacao($observacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtivo', array());

        return parent::getAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setAtivo($ativo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtivo', array($ativo));

        return parent::setAtivo($ativo);
    }

    /**
     * {@inheritDoc}
     */
    public function getInformacoesDocumento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInformacoesDocumento', array());

        return parent::getInformacoesDocumento();
    }

    /**
     * {@inheritDoc}
     */
    public function setInformacoesDocumento($informacoesDocumento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInformacoesDocumento', array($informacoesDocumento));

        return parent::setInformacoesDocumento($informacoesDocumento);
    }

    /**
     * {@inheritDoc}
     */
    public function getEncaminhamentos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEncaminhamentos', array());

        return parent::getEncaminhamentos();
    }

    /**
     * {@inheritDoc}
     */
    public function setEncaminhamentos($encaminhamentos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEncaminhamentos', array($encaminhamentos));

        return parent::setEncaminhamentos($encaminhamentos);
    }

    /**
     * {@inheritDoc}
     */
    public function getEncaminhado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEncaminhado', array());

        return parent::getEncaminhado();
    }

}
