<?php

namespace Proxies\__CG__\SME\FilaUnicaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Vaga extends \SME\FilaUnicaBundle\Entity\Vaga implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'unidadeEscolar', 'anoEscolar', 'periodoDia', 'inscricaoEmChamada', 'historicoChamadas', 'dataCadastro', 'dataModificacao', 'dataMatricula', 'matriculaConfirmada', 'observacao', 'pessoaCadastro', 'pessoaModificacao', 'ativo');
        }

        return array('__isInitialized__', 'id', 'unidadeEscolar', 'anoEscolar', 'periodoDia', 'inscricaoEmChamada', 'historicoChamadas', 'dataCadastro', 'dataModificacao', 'dataMatricula', 'matriculaConfirmada', 'observacao', 'pessoaCadastro', 'pessoaModificacao', 'ativo');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Vaga $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUnidadeEscolar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnidadeEscolar', array());

        return parent::getUnidadeEscolar();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnidadeEscolar(\SME\FilaUnicaBundle\Entity\UnidadeEscolar $unidadeEscolar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnidadeEscolar', array($unidadeEscolar));

        return parent::setUnidadeEscolar($unidadeEscolar);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnoEscolar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnoEscolar', array());

        return parent::getAnoEscolar();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnoEscolar(\SME\FilaUnicaBundle\Entity\AnoEscolar $anoEscolar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnoEscolar', array($anoEscolar));

        return parent::setAnoEscolar($anoEscolar);
    }

    /**
     * {@inheritDoc}
     */
    public function getInscricaoEmChamada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInscricaoEmChamada', array());

        return parent::getInscricaoEmChamada();
    }

    /**
     * {@inheritDoc}
     */
    public function setInscricaoEmChamada(\SME\FilaUnicaBundle\Entity\Inscricao $inscricaoChamada = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInscricaoEmChamada', array($inscricaoChamada));

        return parent::setInscricaoEmChamada($inscricaoChamada);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataCadastro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataCadastro', array());

        return parent::getDataCadastro();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataCadastro($dataCadastro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataCadastro', array($dataCadastro));

        return parent::setDataCadastro($dataCadastro);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataModificacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataModificacao', array());

        return parent::getDataModificacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataModificacao(\DateTime $dataModificacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataModificacao', array($dataModificacao));

        return parent::setDataModificacao($dataModificacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataMatricula()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataMatricula', array());

        return parent::getDataMatricula();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataMatricula(\DateTime $dataMatricula = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataMatricula', array($dataMatricula));

        return parent::setDataMatricula($dataMatricula);
    }

    /**
     * {@inheritDoc}
     */
    public function getPeriodoDia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeriodoDia', array());

        return parent::getPeriodoDia();
    }

    /**
     * {@inheritDoc}
     */
    public function setPeriodoDia(\SME\CommonsBundle\Entity\PeriodoDia $periodoDia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPeriodoDia', array($periodoDia));

        return parent::setPeriodoDia($periodoDia);
    }

    /**
     * {@inheritDoc}
     */
    public function getMatriculaConfirmada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatriculaConfirmada', array());

        return parent::getMatriculaConfirmada();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatriculaConfirmada($matriculaConfirmada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatriculaConfirmada', array($matriculaConfirmada));

        return parent::setMatriculaConfirmada($matriculaConfirmada);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservacao', array());

        return parent::getObservacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservacao($observacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservacao', array($observacao));

        return parent::setObservacao($observacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getPessoaCadastro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPessoaCadastro', array());

        return parent::getPessoaCadastro();
    }

    /**
     * {@inheritDoc}
     */
    public function setPessoaCadastro($pessoaCadastro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPessoaCadastro', array($pessoaCadastro));

        return parent::setPessoaCadastro($pessoaCadastro);
    }

    /**
     * {@inheritDoc}
     */
    public function getPessoaModificacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPessoaModificacao', array());

        return parent::getPessoaModificacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setPessoaModificacao($pessoaModificacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPessoaModificacao', array($pessoaModificacao));

        return parent::setPessoaModificacao($pessoaModificacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtivo', array());

        return parent::getAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setAtivo($ativo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtivo', array($ativo));

        return parent::setAtivo($ativo);
    }

    /**
     * {@inheritDoc}
     */
    public function getHistoricoChamadas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHistoricoChamadas', array());

        return parent::getHistoricoChamadas();
    }

    /**
     * {@inheritDoc}
     */
    public function jsonSerialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'jsonSerialize', array());

        return parent::jsonSerialize();
    }

}
