<?php

namespace Proxies\__CG__\SME\DGPContratacaoBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Processo extends \SME\DGPContratacaoBundle\Entity\Processo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'nome', 'tipoProcesso', 'numeroEdital', 'anoEdital', 'decretoHomologacao', 'dataHomologacao', 'edicaoJornalHomologacao', 'dataPublicacaoHomologacao', 'decretoProrrogacao', 'dataProrrogacao', 'edicaoJornalProrrogacao', 'dataPublicacaoProrrogacao', 'dataEncerramento', 'ativo', 'cargos', 'convocacoes');
        }

        return array('__isInitialized__', 'id', 'nome', 'tipoProcesso', 'numeroEdital', 'anoEdital', 'decretoHomologacao', 'dataHomologacao', 'edicaoJornalHomologacao', 'dataPublicacaoHomologacao', 'decretoProrrogacao', 'dataProrrogacao', 'edicaoJornalProrrogacao', 'dataPublicacaoProrrogacao', 'dataEncerramento', 'ativo', 'cargos', 'convocacoes');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Processo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', array());

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoProcesso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoProcesso', array());

        return parent::getTipoProcesso();
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroEdital()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroEdital', array());

        return parent::getNumeroEdital();
    }

    /**
     * {@inheritDoc}
     */
    public function getAnoEdital()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnoEdital', array());

        return parent::getAnoEdital();
    }

    /**
     * {@inheritDoc}
     */
    public function getEdital()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEdital', array());

        return parent::getEdital();
    }

    /**
     * {@inheritDoc}
     */
    public function getDataEncerramento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataEncerramento', array());

        return parent::getDataEncerramento();
    }

    /**
     * {@inheritDoc}
     */
    public function getAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtivo', array());

        return parent::getAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setNome($nome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome', array($nome));

        return parent::setNome($nome);
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoProcesso(\SME\DGPContratacaoBundle\Entity\TipoProcesso $tipoProcesso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoProcesso', array($tipoProcesso));

        return parent::setTipoProcesso($tipoProcesso);
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroEdital($numeroEdital)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroEdital', array($numeroEdital));

        return parent::setNumeroEdital($numeroEdital);
    }

    /**
     * {@inheritDoc}
     */
    public function setAnoEdital($anoEdital)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnoEdital', array($anoEdital));

        return parent::setAnoEdital($anoEdital);
    }

    /**
     * {@inheritDoc}
     */
    public function setDataEncerramento(\DateTime $dataEncerramento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataEncerramento', array($dataEncerramento));

        return parent::setDataEncerramento($dataEncerramento);
    }

    /**
     * {@inheritDoc}
     */
    public function setAtivo($ativo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtivo', array($ativo));

        return parent::setAtivo($ativo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCargos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCargos', array());

        return parent::getCargos();
    }

    /**
     * {@inheritDoc}
     */
    public function getConvocacoes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConvocacoes', array());

        return parent::getConvocacoes();
    }

    /**
     * {@inheritDoc}
     */
    public function getDecretoHomologacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDecretoHomologacao', array());

        return parent::getDecretoHomologacao();
    }

    /**
     * {@inheritDoc}
     */
    public function getDataHomologacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataHomologacao', array());

        return parent::getDataHomologacao();
    }

    /**
     * {@inheritDoc}
     */
    public function getEdicaoJornalHomologacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEdicaoJornalHomologacao', array());

        return parent::getEdicaoJornalHomologacao();
    }

    /**
     * {@inheritDoc}
     */
    public function getDataPublicacaoHomologacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataPublicacaoHomologacao', array());

        return parent::getDataPublicacaoHomologacao();
    }

    /**
     * {@inheritDoc}
     */
    public function getDecretoProrrogacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDecretoProrrogacao', array());

        return parent::getDecretoProrrogacao();
    }

    /**
     * {@inheritDoc}
     */
    public function getDataProrrogacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataProrrogacao', array());

        return parent::getDataProrrogacao();
    }

    /**
     * {@inheritDoc}
     */
    public function getEdicaoJornalProrrogacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEdicaoJornalProrrogacao', array());

        return parent::getEdicaoJornalProrrogacao();
    }

    /**
     * {@inheritDoc}
     */
    public function getDataPublicacaoProrrogacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataPublicacaoProrrogacao', array());

        return parent::getDataPublicacaoProrrogacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDecretoHomologacao($decretoHomologacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDecretoHomologacao', array($decretoHomologacao));

        return parent::setDecretoHomologacao($decretoHomologacao);
    }

    /**
     * {@inheritDoc}
     */
    public function setDataHomologacao($dataHomologacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataHomologacao', array($dataHomologacao));

        return parent::setDataHomologacao($dataHomologacao);
    }

    /**
     * {@inheritDoc}
     */
    public function setEdicaoJornalHomologacao($edicaoJornalHomologacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEdicaoJornalHomologacao', array($edicaoJornalHomologacao));

        return parent::setEdicaoJornalHomologacao($edicaoJornalHomologacao);
    }

    /**
     * {@inheritDoc}
     */
    public function setDataPublicacaoHomologacao($dataPublicacaoHomologacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataPublicacaoHomologacao', array($dataPublicacaoHomologacao));

        return parent::setDataPublicacaoHomologacao($dataPublicacaoHomologacao);
    }

    /**
     * {@inheritDoc}
     */
    public function setDecretoProrrogacao($decretoProrrogacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDecretoProrrogacao', array($decretoProrrogacao));

        return parent::setDecretoProrrogacao($decretoProrrogacao);
    }

    /**
     * {@inheritDoc}
     */
    public function setDataProrrogacao($dataProrrogacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataProrrogacao', array($dataProrrogacao));

        return parent::setDataProrrogacao($dataProrrogacao);
    }

    /**
     * {@inheritDoc}
     */
    public function setEdicaoJornalProrrogacao($edicaoJornalProrrogacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEdicaoJornalProrrogacao', array($edicaoJornalProrrogacao));

        return parent::setEdicaoJornalProrrogacao($edicaoJornalProrrogacao);
    }

    /**
     * {@inheritDoc}
     */
    public function setDataPublicacaoProrrogacao($dataPublicacaoProrrogacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataPublicacaoProrrogacao', array($dataPublicacaoProrrogacao));

        return parent::setDataPublicacaoProrrogacao($dataPublicacaoProrrogacao);
    }

}
