<?php

namespace Proxies\__CG__\SME\FilaUnicaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Inscricao extends \SME\FilaUnicaBundle\Entity\Inscricao implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'tipoInscricao', 'protocolo', 'crianca', 'zoneamento', 'unidadeOrigem', 'unidadeDestino', 'unidadeDestinoAlternativa', 'dataCadastro', 'atendente', 'dataModificacao', 'pessoaUltimaModificacao', 'dataChamada', 'anoEscolar', 'periodoDia', 'status', 'rendaPerCapita', 'situacaoFamiliar', 'rendaPontuada', 'vagaOfertada', 'codigoAluno', 'dataMatricula', 'processoJudicial', 'numeroOrdemJudicial', 'dataProcessoJudicial', 'movimentacaoInterna', 'ativo', 'historico', 'rendaDetalhada');
        }

        return array('__isInitialized__', 'id', 'tipoInscricao', 'protocolo', 'crianca', 'zoneamento', 'unidadeOrigem', 'unidadeDestino', 'unidadeDestinoAlternativa', 'dataCadastro', 'atendente', 'dataModificacao', 'pessoaUltimaModificacao', 'dataChamada', 'anoEscolar', 'periodoDia', 'status', 'rendaPerCapita', 'situacaoFamiliar', 'rendaPontuada', 'vagaOfertada', 'codigoAluno', 'dataMatricula', 'processoJudicial', 'numeroOrdemJudicial', 'dataProcessoJudicial', 'movimentacaoInterna', 'ativo', 'historico', 'rendaDetalhada');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Inscricao $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function calcularPontuacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'calcularPontuacao', array());

        return parent::calcularPontuacao();
    }

    /**
     * {@inheritDoc}
     */
    public function visivel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'visivel', array());

        return parent::visivel();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getHistorico()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHistorico', array());

        return parent::getHistorico();
    }

    /**
     * {@inheritDoc}
     */
    public function setHistorico($historico)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHistorico', array($historico));

        return parent::setHistorico($historico);
    }

    /**
     * {@inheritDoc}
     */
    public function getRendaDetalhada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRendaDetalhada', array());

        return parent::getRendaDetalhada();
    }

    /**
     * {@inheritDoc}
     */
    public function setRendaDetalhada($rendaDetalhada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRendaDetalhada', array($rendaDetalhada));

        return parent::setRendaDetalhada($rendaDetalhada);
    }

    /**
     * {@inheritDoc}
     */
    public function getRendaPontuada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRendaPontuada', array());

        return parent::getRendaPontuada();
    }

    /**
     * {@inheritDoc}
     */
    public function setRendaPontuada($rendaPontuada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRendaPontuada', array($rendaPontuada));

        return parent::setRendaPontuada($rendaPontuada);
    }

    /**
     * {@inheritDoc}
     */
    public function getProtocolo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProtocolo', array());

        return parent::getProtocolo();
    }

    /**
     * {@inheritDoc}
     */
    public function setProtocolo($protocolo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProtocolo', array($protocolo));

        return parent::setProtocolo($protocolo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCrianca()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCrianca', array());

        return parent::getCrianca();
    }

    /**
     * {@inheritDoc}
     */
    public function setCrianca(\SME\CommonsBundle\Entity\PessoaFisica $crianca)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCrianca', array($crianca));

        return parent::setCrianca($crianca);
    }

    /**
     * {@inheritDoc}
     */
    public function getZoneamento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZoneamento', array());

        return parent::getZoneamento();
    }

    /**
     * {@inheritDoc}
     */
    public function setZoneamento(\SME\FilaUnicaBundle\Entity\Zoneamento $zoneamento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZoneamento', array($zoneamento));

        return parent::setZoneamento($zoneamento);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataCadastro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataCadastro', array());

        return parent::getDataCadastro();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataCadastro(\DateTime $dataCadastro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataCadastro', array($dataCadastro));

        return parent::setDataCadastro($dataCadastro);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataModificacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataModificacao', array());

        return parent::getDataModificacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataModificacao(\DateTime $dataModificacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataModificacao', array($dataModificacao));

        return parent::setDataModificacao($dataModificacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getPessoaUltimaModificacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPessoaUltimaModificacao', array());

        return parent::getPessoaUltimaModificacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setPessoaUltimaModificacao($pessoaUltimaModificacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPessoaUltimaModificacao', array($pessoaUltimaModificacao));

        return parent::setPessoaUltimaModificacao($pessoaUltimaModificacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataChamada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataChamada', array());

        return parent::getDataChamada();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataChamada(\DateTime $dataChamada = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataChamada', array($dataChamada));

        return parent::setDataChamada($dataChamada);
    }

    /**
     * {@inheritDoc}
     */
    public function getAtendente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtendente', array());

        return parent::getAtendente();
    }

    /**
     * {@inheritDoc}
     */
    public function setAtendente(\SME\CommonsBundle\Entity\PessoaFisica $atendente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtendente', array($atendente));

        return parent::setAtendente($atendente);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnoEscolar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnoEscolar', array());

        return parent::getAnoEscolar();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnoEscolar(\SME\FilaUnicaBundle\Entity\AnoEscolar $anoEscolar = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnoEscolar', array($anoEscolar));

        return parent::setAnoEscolar($anoEscolar);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(\SME\FilaUnicaBundle\Entity\Status $status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnidadeOrigem()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnidadeOrigem', array());

        return parent::getUnidadeOrigem();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnidadeOrigem(\SME\FilaUnicaBundle\Entity\UnidadeEscolar $unidadeOrigem)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnidadeOrigem', array($unidadeOrigem));

        return parent::setUnidadeOrigem($unidadeOrigem);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnidadeDestino()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnidadeDestino', array());

        return parent::getUnidadeDestino();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnidadeDestino(\SME\FilaUnicaBundle\Entity\UnidadeEscolar $unidadeDestino)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnidadeDestino', array($unidadeDestino));

        return parent::setUnidadeDestino($unidadeDestino);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnidadeDestinoAlternativa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnidadeDestinoAlternativa', array());

        return parent::getUnidadeDestinoAlternativa();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnidadeDestinoAlternativa($unidadeDestinoAlternativa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnidadeDestinoAlternativa', array($unidadeDestinoAlternativa));

        return parent::setUnidadeDestinoAlternativa($unidadeDestinoAlternativa);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoInscricao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoInscricao', array());

        return parent::getTipoInscricao();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoInscricao(\SME\FilaUnicaBundle\Entity\TipoInscricao $tipoInscricao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoInscricao', array($tipoInscricao));

        return parent::setTipoInscricao($tipoInscricao);
    }

    /**
     * {@inheritDoc}
     */
    public function getPeriodoDia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeriodoDia', array());

        return parent::getPeriodoDia();
    }

    /**
     * {@inheritDoc}
     */
    public function setPeriodoDia(\SME\CommonsBundle\Entity\PeriodoDia $periodoDia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPeriodoDia', array($periodoDia));

        return parent::setPeriodoDia($periodoDia);
    }

    /**
     * {@inheritDoc}
     */
    public function getRendaPerCapita()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRendaPerCapita', array());

        return parent::getRendaPerCapita();
    }

    /**
     * {@inheritDoc}
     */
    public function setRendaPerCapita($rendaPerCapita)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRendaPerCapita', array($rendaPerCapita));

        return parent::setRendaPerCapita($rendaPerCapita);
    }

    /**
     * {@inheritDoc}
     */
    public function getSituacaoFamiliar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSituacaoFamiliar', array());

        return parent::getSituacaoFamiliar();
    }

    /**
     * {@inheritDoc}
     */
    public function setSituacaoFamiliar(\SME\FilaUnicaBundle\Entity\SituacaoFamiliar $situacaoFamiliar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSituacaoFamiliar', array($situacaoFamiliar));

        return parent::setSituacaoFamiliar($situacaoFamiliar);
    }

    /**
     * {@inheritDoc}
     */
    public function getVagaOfertada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVagaOfertada', array());

        return parent::getVagaOfertada();
    }

    /**
     * {@inheritDoc}
     */
    public function setVagaOfertada(\SME\FilaUnicaBundle\Entity\Vaga $vagaOfertada = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVagaOfertada', array($vagaOfertada));

        return parent::setVagaOfertada($vagaOfertada);
    }

    /**
     * {@inheritDoc}
     */
    public function getAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtivo', array());

        return parent::getAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setAtivo($ativo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtivo', array($ativo));

        return parent::setAtivo($ativo);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroOrdemJudicial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroOrdemJudicial', array());

        return parent::getNumeroOrdemJudicial();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroOrdemJudicial($ordemJudicial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroOrdemJudicial', array($ordemJudicial));

        return parent::setNumeroOrdemJudicial($ordemJudicial);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigoAluno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigoAluno', array());

        return parent::getCodigoAluno();
    }

    /**
     * {@inheritDoc}
     */
    public function getDataMatricula()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataMatricula', array());

        return parent::getDataMatricula();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigoAluno($codigoAluno)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigoAluno', array($codigoAluno));

        return parent::setCodigoAluno($codigoAluno);
    }

    /**
     * {@inheritDoc}
     */
    public function setDataMatricula($dataMatricula)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataMatricula', array($dataMatricula));

        return parent::setDataMatricula($dataMatricula);
    }

    /**
     * {@inheritDoc}
     */
    public function getProcessoJudicial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProcessoJudicial', array());

        return parent::getProcessoJudicial();
    }

    /**
     * {@inheritDoc}
     */
    public function setProcessoJudicial($processoJudicial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProcessoJudicial', array($processoJudicial));

        return parent::setProcessoJudicial($processoJudicial);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataProcessoJudicial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataProcessoJudicial', array());

        return parent::getDataProcessoJudicial();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataProcessoJudicial($dataProcessoJudicial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataProcessoJudicial', array($dataProcessoJudicial));

        return parent::setDataProcessoJudicial($dataProcessoJudicial);
    }

    /**
     * {@inheritDoc}
     */
    public function getMovimentacaoInterna()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMovimentacaoInterna', array());

        return parent::getMovimentacaoInterna();
    }

    /**
     * {@inheritDoc}
     */
    public function setMovimentacaoInterna($movimentacaoInterna)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMovimentacaoInterna', array($movimentacaoInterna));

        return parent::setMovimentacaoInterna($movimentacaoInterna);
    }

    /**
     * {@inheritDoc}
     */
    public function jsonSerialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'jsonSerialize', array());

        return parent::jsonSerialize();
    }

}
