<?php

namespace Proxies\__CG__\SME\CommonsBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PessoaFisica extends \SME\CommonsBundle\Entity\PessoaFisica implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'numeroRg', 'orgaoExpedidorRg', 'dataExpedicaoRg', 'pisPasep', 'numeroTituloEleitor', 'zonaTituloEleitor', 'secaoTituloEleitor', 'naturalidade', 'nacionalidade', 'estadoCivil', 'nomeMae', 'nomePai', 'raca', 'certidaoNascimento', 'formacoes', 'relacoes', 'profissao', 'carteiraTrabalhoNumero', 'carteiraTrabalhoSerie', 'carteiraTrabalhoDataExepdicao', 'carteiraTrabalhoEstado', 'vinculosTrabalho', 'particularidades');
        }

        return array('__isInitialized__', 'numeroRg', 'orgaoExpedidorRg', 'dataExpedicaoRg', 'pisPasep', 'numeroTituloEleitor', 'zonaTituloEleitor', 'secaoTituloEleitor', 'naturalidade', 'nacionalidade', 'estadoCivil', 'nomeMae', 'nomePai', 'raca', 'certidaoNascimento', 'formacoes', 'relacoes', 'profissao', 'carteiraTrabalhoNumero', 'carteiraTrabalhoSerie', 'carteiraTrabalhoDataExepdicao', 'carteiraTrabalhoEstado', 'vinculosTrabalho', 'particularidades');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PessoaFisica $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getNumeroRg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroRg', array());

        return parent::getNumeroRg();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroRg($numeroRg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroRg', array($numeroRg));

        return parent::setNumeroRg($numeroRg);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrgaoExpedidorRg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrgaoExpedidorRg', array());

        return parent::getOrgaoExpedidorRg();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrgaoExpedidorRg($orgaoExpedidorRg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrgaoExpedidorRg', array($orgaoExpedidorRg));

        return parent::setOrgaoExpedidorRg($orgaoExpedidorRg);
    }

    /**
     * {@inheritDoc}
     */
    public function getPisPasep()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPisPasep', array());

        return parent::getPisPasep();
    }

    /**
     * {@inheritDoc}
     */
    public function setPisPasep($pisPasep)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPisPasep', array($pisPasep));

        return parent::setPisPasep($pisPasep);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroTituloEleitor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroTituloEleitor', array());

        return parent::getNumeroTituloEleitor();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroTituloEleitor($numeroTituloEleitor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroTituloEleitor', array($numeroTituloEleitor));

        return parent::setNumeroTituloEleitor($numeroTituloEleitor);
    }

    /**
     * {@inheritDoc}
     */
    public function getZonaTituloEleitor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZonaTituloEleitor', array());

        return parent::getZonaTituloEleitor();
    }

    /**
     * {@inheritDoc}
     */
    public function setZonaTituloEleitor($zonaTituloEleitor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZonaTituloEleitor', array($zonaTituloEleitor));

        return parent::setZonaTituloEleitor($zonaTituloEleitor);
    }

    /**
     * {@inheritDoc}
     */
    public function getSecaoTituloEleitor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSecaoTituloEleitor', array());

        return parent::getSecaoTituloEleitor();
    }

    /**
     * {@inheritDoc}
     */
    public function setSecaoTituloEleitor($secaoTituloEleitor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSecaoTituloEleitor', array($secaoTituloEleitor));

        return parent::setSecaoTituloEleitor($secaoTituloEleitor);
    }

    /**
     * {@inheritDoc}
     */
    public function getNaturalidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNaturalidade', array());

        return parent::getNaturalidade();
    }

    /**
     * {@inheritDoc}
     */
    public function setNaturalidade($naturalidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNaturalidade', array($naturalidade));

        return parent::setNaturalidade($naturalidade);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstadoCivil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstadoCivil', array());

        return parent::getEstadoCivil();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstadoCivil(\SME\CommonsBundle\Entity\EstadoCivil $estadoCivil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstadoCivil', array($estadoCivil));

        return parent::setEstadoCivil($estadoCivil);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomeMae()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomeMae', array());

        return parent::getNomeMae();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomeMae($nomeMae)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomeMae', array($nomeMae));

        return parent::setNomeMae($nomeMae);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomePai()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomePai', array());

        return parent::getNomePai();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomePai($nomePai)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomePai', array($nomePai));

        return parent::setNomePai($nomePai);
    }

    /**
     * {@inheritDoc}
     */
    public function getRaca()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRaca', array());

        return parent::getRaca();
    }

    /**
     * {@inheritDoc}
     */
    public function setRaca(\SME\CommonsBundle\Entity\Raca $raca)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRaca', array($raca));

        return parent::setRaca($raca);
    }

    /**
     * {@inheritDoc}
     */
    public function getNacionalidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNacionalidade', array());

        return parent::getNacionalidade();
    }

    /**
     * {@inheritDoc}
     */
    public function setNacionalidade($nacionalidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNacionalidade', array($nacionalidade));

        return parent::setNacionalidade($nacionalidade);
    }

    /**
     * {@inheritDoc}
     */
    public function getCertidaoNascimento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCertidaoNascimento', array());

        return parent::getCertidaoNascimento();
    }

    /**
     * {@inheritDoc}
     */
    public function getTermoCertidaoNascimento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTermoCertidaoNascimento', array());

        return parent::getTermoCertidaoNascimento();
    }

    /**
     * {@inheritDoc}
     */
    public function getLivroCertidaoNascimento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLivroCertidaoNascimento', array());

        return parent::getLivroCertidaoNascimento();
    }

    /**
     * {@inheritDoc}
     */
    public function getFolhaCertidaoNascimento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFolhaCertidaoNascimento', array());

        return parent::getFolhaCertidaoNascimento();
    }

    /**
     * {@inheritDoc}
     */
    public function setCertidaoNascimento($certidaoNascimento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCertidaoNascimento', array($certidaoNascimento));

        return parent::setCertidaoNascimento($certidaoNascimento);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataExpedicaoRg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataExpedicaoRg', array());

        return parent::getDataExpedicaoRg();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataExpedicaoRg($dataExpedicaoRg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataExpedicaoRg', array($dataExpedicaoRg));

        return parent::setDataExpedicaoRg($dataExpedicaoRg);
    }

    /**
     * {@inheritDoc}
     */
    public function getRelacoes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelacoes', array());

        return parent::getRelacoes();
    }

    /**
     * {@inheritDoc}
     */
    public function getFormacoes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormacoes', array());

        return parent::getFormacoes();
    }

    /**
     * {@inheritDoc}
     */
    public function getProfissao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfissao', array());

        return parent::getProfissao();
    }

    /**
     * {@inheritDoc}
     */
    public function getCarteiraTrabalhoDataExepdicao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCarteiraTrabalhoDataExepdicao', array());

        return parent::getCarteiraTrabalhoDataExepdicao();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfissao($profissao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfissao', array($profissao));

        return parent::setProfissao($profissao);
    }

    /**
     * {@inheritDoc}
     */
    public function setCarteiraTrabalhoDataExepdicao($carteiraTrabalhoDataExepdicao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCarteiraTrabalhoDataExepdicao', array($carteiraTrabalhoDataExepdicao));

        return parent::setCarteiraTrabalhoDataExepdicao($carteiraTrabalhoDataExepdicao);
    }

    /**
     * {@inheritDoc}
     */
    public function getCarteiraTrabalhoNumero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCarteiraTrabalhoNumero', array());

        return parent::getCarteiraTrabalhoNumero();
    }

    /**
     * {@inheritDoc}
     */
    public function setCarteiraTrabalhoNumero($ctps_num)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCarteiraTrabalhoNumero', array($ctps_num));

        return parent::setCarteiraTrabalhoNumero($ctps_num);
    }

    /**
     * {@inheritDoc}
     */
    public function getCarteiraTrabalhoSerie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCarteiraTrabalhoSerie', array());

        return parent::getCarteiraTrabalhoSerie();
    }

    /**
     * {@inheritDoc}
     */
    public function setCarteiraTrabalhoSerie($ctps_serie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCarteiraTrabalhoSerie', array($ctps_serie));

        return parent::setCarteiraTrabalhoSerie($ctps_serie);
    }

    /**
     * {@inheritDoc}
     */
    public function getCarteiraTrabalhoDataExpedicao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCarteiraTrabalhoDataExpedicao', array());

        return parent::getCarteiraTrabalhoDataExpedicao();
    }

    /**
     * {@inheritDoc}
     */
    public function setCarteiraTrabalhoDataExpedicao($ctps_data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCarteiraTrabalhoDataExpedicao', array($ctps_data));

        return parent::setCarteiraTrabalhoDataExpedicao($ctps_data);
    }

    /**
     * {@inheritDoc}
     */
    public function getCarteiraTrabalhoEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCarteiraTrabalhoEstado', array());

        return parent::getCarteiraTrabalhoEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setCarteiraTrabalhoEstado(\SME\CommonsBundle\Entity\Estado $ctps_estado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCarteiraTrabalhoEstado', array($ctps_estado));

        return parent::setCarteiraTrabalhoEstado($ctps_estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getVinculosTrabalho()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVinculosTrabalho', array());

        return parent::getVinculosTrabalho();
    }

    /**
     * {@inheritDoc}
     */
    public function getParticularidades()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParticularidades', array());

        return parent::getParticularidades();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', array());

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function setNome($nome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome', array($nome));

        return parent::setNome($nome);
    }

    /**
     * {@inheritDoc}
     */
    public function getApelido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApelido', array());

        return parent::getApelido();
    }

    /**
     * {@inheritDoc}
     */
    public function setApelido($apelido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApelido', array($apelido));

        return parent::setApelido($apelido);
    }

    /**
     * {@inheritDoc}
     */
    public function getCpfCnpj()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCpfCnpj', array());

        return parent::getCpfCnpj();
    }

    /**
     * {@inheritDoc}
     */
    public function setCpfCnpj($cpfCnpj)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCpfCnpj', array($cpfCnpj));

        return parent::setCpfCnpj($cpfCnpj);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataNascimento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataNascimento', array());

        return parent::getDataNascimento();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataNascimento(\DateTime $dataNascimento = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataNascimento', array($dataNascimento));

        return parent::setDataNascimento($dataNascimento);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', array());

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario($usuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', array($usuario));

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndereco()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndereco', array());

        return parent::getEndereco();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndereco(\SME\CommonsBundle\Entity\Endereco $endereco)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndereco', array($endereco));

        return parent::setEndereco($endereco);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefones', array());

        return parent::getTelefones();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefones($telefones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefones', array($telefones));

        return parent::setTelefones($telefones);
    }

    /**
     * {@inheritDoc}
     */
    public function getAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtivo', array());

        return parent::getAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setAtivo($ativo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtivo', array($ativo));

        return parent::setAtivo($ativo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefone', array());

        return parent::getTelefone();
    }

    /**
     * {@inheritDoc}
     */
    public function getCelular()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCelular', array());

        return parent::getCelular();
    }

    /**
     * {@inheritDoc}
     */
    public function serialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'serialize', array());

        return parent::serialize();
    }

    /**
     * {@inheritDoc}
     */
    public function unserialize($serialized)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'unserialize', array($serialized));

        return parent::unserialize($serialized);
    }

    /**
     * {@inheritDoc}
     */
    public function jsonSerialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'jsonSerialize', array());

        return parent::jsonSerialize();
    }

}
