<?php

namespace Proxies\__CG__\SME\DGPFormacaoBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Formacao extends \SME\DGPFormacaoBundle\Entity\Formacao implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'nome', 'nomeCertificado', 'publicoAlvo', 'cargaHoraria', 'limiteVagas', 'dataInicioInscricao', 'dataTerminoInscricao', 'dataInicioFormacao', 'dataTerminoFormacao', 'descricao', 'aberto', 'publicado', 'modeloCertificado', 'ativo', 'matriculas', 'encontros');
        }

        return array('__isInitialized__', 'id', 'nome', 'nomeCertificado', 'publicoAlvo', 'cargaHoraria', 'limiteVagas', 'dataInicioInscricao', 'dataTerminoInscricao', 'dataInicioFormacao', 'dataTerminoFormacao', 'descricao', 'aberto', 'publicado', 'modeloCertificado', 'ativo', 'matriculas', 'encontros');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Formacao $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', array());

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function setNome($nome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome', array($nome));

        return parent::setNome($nome);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomeCertificado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomeCertificado', array());

        return parent::getNomeCertificado();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomeCertificado($nomeCertificado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomeCertificado', array($nomeCertificado));

        return parent::setNomeCertificado($nomeCertificado);
    }

    /**
     * {@inheritDoc}
     */
    public function getPublicoAlvo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublicoAlvo', array());

        return parent::getPublicoAlvo();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublicoAlvo($publicoAlvo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublicoAlvo', array($publicoAlvo));

        return parent::setPublicoAlvo($publicoAlvo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCargaHoraria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCargaHoraria', array());

        return parent::getCargaHoraria();
    }

    /**
     * {@inheritDoc}
     */
    public function setCargaHoraria($cargaHoraria)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCargaHoraria', array($cargaHoraria));

        return parent::setCargaHoraria($cargaHoraria);
    }

    /**
     * {@inheritDoc}
     */
    public function getLimiteVagas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLimiteVagas', array());

        return parent::getLimiteVagas();
    }

    /**
     * {@inheritDoc}
     */
    public function setLimiteVagas($limiteVagas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLimiteVagas', array($limiteVagas));

        return parent::setLimiteVagas($limiteVagas);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataInicioInscricao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataInicioInscricao', array());

        return parent::getDataInicioInscricao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataInicioInscricao($dataInicioInscricao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataInicioInscricao', array($dataInicioInscricao));

        return parent::setDataInicioInscricao($dataInicioInscricao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataTerminoInscricao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataTerminoInscricao', array());

        return parent::getDataTerminoInscricao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataTerminoInscricao($dataTerminoInscricao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataTerminoInscricao', array($dataTerminoInscricao));

        return parent::setDataTerminoInscricao($dataTerminoInscricao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataInicioFormacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataInicioFormacao', array());

        return parent::getDataInicioFormacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataInicioFormacao($dataInicioFormacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataInicioFormacao', array($dataInicioFormacao));

        return parent::setDataInicioFormacao($dataInicioFormacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataTerminoFormacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataTerminoFormacao', array());

        return parent::getDataTerminoFormacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataTerminoFormacao($dataTerminoFormacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataTerminoFormacao', array($dataTerminoFormacao));

        return parent::setDataTerminoFormacao($dataTerminoFormacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescricao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescricao', array());

        return parent::getDescricao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescricao($descricao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescricao', array($descricao));

        return parent::setDescricao($descricao);
    }

    /**
     * {@inheritDoc}
     */
    public function getAberto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAberto', array());

        return parent::getAberto();
    }

    /**
     * {@inheritDoc}
     */
    public function setAberto($aberto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAberto', array($aberto));

        return parent::setAberto($aberto);
    }

    /**
     * {@inheritDoc}
     */
    public function getPublicado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublicado', array());

        return parent::getPublicado();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublicado($publicado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublicado', array($publicado));

        return parent::setPublicado($publicado);
    }

    /**
     * {@inheritDoc}
     */
    public function getModeloCertificado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModeloCertificado', array());

        return parent::getModeloCertificado();
    }

    /**
     * {@inheritDoc}
     */
    public function setModeloCertificado($modeloCertificado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModeloCertificado', array($modeloCertificado));

        return parent::setModeloCertificado($modeloCertificado);
    }

    /**
     * {@inheritDoc}
     */
    public function getAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtivo', array());

        return parent::getAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setAtivo($ativo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtivo', array($ativo));

        return parent::setAtivo($ativo);
    }

    /**
     * {@inheritDoc}
     */
    public function getMatriculas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatriculas', array());

        return parent::getMatriculas();
    }

    /**
     * {@inheritDoc}
     */
    public function getEncontros()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEncontros', array());

        return parent::getEncontros();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatriculas($matriculas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatriculas', array($matriculas));

        return parent::setMatriculas($matriculas);
    }

    /**
     * {@inheritDoc}
     */
    public function getVagasDisponiveis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVagasDisponiveis', array());

        return parent::getVagasDisponiveis();
    }

    /**
     * {@inheritDoc}
     */
    public function isDataInscricaoValida()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isDataInscricaoValida', array());

        return parent::isDataInscricaoValida();
    }

    /**
     * {@inheritDoc}
     */
    public function isDataFormacaoValida()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isDataFormacaoValida', array());

        return parent::isDataFormacaoValida();
    }

    /**
     * {@inheritDoc}
     */
    public function isDataInscricaoFormacaoValida()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isDataInscricaoFormacaoValida', array());

        return parent::isDataInscricaoFormacaoValida();
    }

    /**
     * {@inheritDoc}
     */
    public function isCargaHorariaValida()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isCargaHorariaValida', array());

        return parent::isCargaHorariaValida();
    }

    /**
     * {@inheritDoc}
     */
    public function jsonSerialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'jsonSerialize', array());

        return parent::jsonSerialize();
    }

}
