(function(){class ProfessorController{constructor(util,$mdDialog,erudioConfig,$timeout,baseService,enturmacaoService,shared){this.util=util;this.shared=shared;this.mdDialog=$mdDialog;this.erudioConfig=erudioConfig;this.baseService=baseService;this.enturmacaoService=enturmacaoService;this.timeout=$timeout;this.permissaoLabel="HOME_PROFESSOR";this.linkModulo="/#!/";this.avaliacoesUrl=erudioConfig.dominio+"/apps/professor/avaliacoes/partials/index.html";this.mediasUrl=erudioConfig.dominio+"/apps/professor/medias/partials/index.html";this.eventosUrl=erudioConfig.dominio+"/apps/professor/eventos/partials/index.html";this.aulasTemplate=erudioConfig.dominio+"/apps/professor/aulas/partials/index.html";this.eventosTemplate=null;this.mediasTemplate=null;this.avaliacoesTemplate=null;this.buscaIcone='search';this.turmaSelecionada=null;this.possuiEnturmacoes=null;this.buscarDisciplinas()}
refresh(){sessionStorage.setItem('turmaSelecionada',JSON.stringify(this.turmaSelecionada));this.enturmacaoService.getAll({encerrado:0,turma:this.turmaSelecionada.turma.id},!0).then((enturmacoes)=>{if(enturmacoes.length>0){sessionStorage.setItem('possuiEnturmacoes',1);this.timeout(()=>{location.reload()},500)}
else{sessionStorage.removeItem('possuiEnturmacoes');sessionStorage.setItem('possuiEnturmacoes',0);this.timeout(()=>{location.reload()},500)}})}
buscarDisciplinas(){this.isQualitativa=!1;this.baseService.buscar('professor/disciplinas',null,!1).then((disciplinas)=>{this.disciplinasLecionadas=disciplinas;disciplinas.forEach((disciplina)=>{var obj=JSON.parse(sessionStorage.getItem('turmaSelecionada'));if(!this.util.isVazio(obj)&&disciplina.id===parseInt(obj.id)){this.turmaSelecionada=disciplina}});if(disciplinas.length===1){this.turmaSelecionada=disciplinas[0]}})}
inserirConteudo(tab){switch(tab){case 'aulas':this.shared.setAbaHome('aulas');$('.btn-home').hide();break;case 'avaliacoes':this.shared.setAbaHome('calendarios');$('.btn-home').hide();if(this.util.isVazio(this.avaliacoesTemplate)){this.avaliacoesTemplate=this.avaliacoesUrl}
break;case 'medias':this.shared.setAbaHome('medias');$('.btn-home').hide();if(this.util.isVazio(this.mediasTemplate)){this.mediasTemplate=this.mediasUrl}
break;case 'eventos':this.shared.setAbaHome('eventos');$('.btn-home').hide();if(this.util.isVazio(this.eventosTemplate)){this.eventosTemplate=this.eventosUrl}
break}}}
ProfessorController.$inject=["Util","$mdDialog","ErudioConfig","$timeout","BaseService","EnturmacaoService","Shared"];angular.module('ProfessorController',['ngMaterial','util','erudioConfig']).controller('ProfessorController',ProfessorController)})();
(function(){class AulaController{constructor(service,util,erudioConfig,$timeout,turmaService,aulaService,diaService,quadroHorarioService,frequenciaService,$http,$mdDialog,$mdMenu,disciplinaCursadaService,shared,scope){this.service=service;this.util=util;this.mdDialog=$mdDialog;this.scope=scope;this.scope.shared=shared;this.erudioConfig=erudioConfig;this.turmaService=turmaService;this.aulaService=aulaService;this.quadroHorarioService=quadroHorarioService;this.frequenciaService=frequenciaService;this.diaService=diaService;this.timeout=$timeout;this.http=$http;this.mdMenu=$mdMenu;this.turma=null;this.disciplina=JSON.parse(sessionStorage.getItem('turmaSelecionada'));this.horarios=[];this.menuHorarios=[];this.possuiEnturmacoes=parseInt(sessionStorage.getItem('possuiEnturmacoes'));this.aulasSemana={segunda:[],terca:[],quarta:[],quinta:[],sexta:[]};this.calendario=null;this.mesCalendario=[];this.disciplinaCursadaService=disciplinaCursadaService;this.diaSelecionado=null;this.semanaCalendario=[];this.permissaoLabel="HOME_PROFESSOR";this.nomeForm="calendarioForm";this.aula=null;this.aulas=null;this.mes=null;this.ano=null;this.disciplinaEscolhida=!1;this.delayUpdate=null;this.conteudo=null;this.chamada=!1;this.alunos=null;this.anotacoes=null;this.alunoSelecionado=null;this.iniciar()}
verificarPermissao(){return this.util.verificaPermissao(this.permissaoLabel)}
verificaEscrita(){return this.util.verificaEscrita(this.permissaoLabel)}
validarEscrita(opcao){if(opcao.validarEscrita){return this.util.validarEscrita(opcao.opcao,this.opcoes,this.escrita)}else{return!0}}
resetCalendario(){this.mesCalendario=[];this.semanaCalendario=[]}
preparaCalendario(mes,ano){var self=this;if(this.util.isVazio(mes)&&this.util.isVazio(ano)){var dateBase=new Date();this.mes=dateBase.getMonth();this.ano=dateBase.getFullYear();this.preparaCalendario(this.mes,this.ano)}else{this.diaS=1;this.mes=mes;this.ano=ano;this.diaSemana=new Date(this.ano,this.mes,this.diaS).getDay();this.counterCalendario=this.diaSemana;this.gapInicio=this.diaSemana;this.diasMes=this.util.diasNoMes(this.mes,this.ano);this.semanaCalendario=new Array(this.gapInicio);this.nomeMes=this.util.nomeMes(this.mes);this.timeout(function(){self.linkPaginacao()},500);self.buscarEventos()}};buscarCalendario(){if(!this.util.isVazio(sessionStorage.getItem('turmaSelecionada'))){this.disciplinaEscolhida=!0;var self=this;var obj=JSON.parse(sessionStorage.getItem('turmaSelecionada'));this.horarios=[];this.menuHorarios=[];this.aulasSemana={segunda:[],terca:[],quarta:[],quinta:[],sexta:[]};this.turmaService.get(obj.turma.id,!0).then((turma)=>{this.turma=turma;this.quadroHorarioService.getHorarios(turma.quadroHorario.id,turma.id,!0).then((horarios)=>{for(var i=0;i<horarios.length;i++){horarios[i].inicio=this.util.converteHora(horarios[i].inicio);if(!this.util.isVazio(horarios[i].disciplinaAlocada)){horarios[i].inicio=this.util.converteHora(horarios[i].inicio);switch(horarios[i].diaSemana.diaSemana){case "2":if(horarios[i].disciplinaAlocada.id===this.disciplina.id){this.aulasSemana.segunda.push(horarios[i])}
break;case "3":if(horarios[i].disciplinaAlocada.id===this.disciplina.id){this.aulasSemana.terca.push(horarios[i])}
break;case "4":if(horarios[i].disciplinaAlocada.id===this.disciplina.id){this.aulasSemana.quarta.push(horarios[i])}
break;case "5":if(horarios[i].disciplinaAlocada.id===this.disciplina.id){this.aulasSemana.quinta.push(horarios[i])}
break;case "6":if(horarios[i].disciplinaAlocada.id===this.disciplina.id){this.aulasSemana.sexta.push(horarios[i])}
break;default:return!1;break}}}});this.calendario=turma.calendario;this.preparaCalendario()})}}
mostraBotaoVoltar(){$('.btn-home').show();$('.btn-home').click(()=>{$('.btn-home').hide();this.fecharForm()})}
escolherDia(dia,horarios){if(horarios.length>0&&dia.efetivo!==undefined&&dia.efetivo){this.mostraBotaoVoltar();this.diaSelecionado=dia;var obj=JSON.parse(sessionStorage.getItem('turmaSelecionada'));this.aulaService.getAll({dia:dia.id,disciplina:obj.id},!0).then((aulas)=>{if(aulas.length===0){horarios.forEach((horario,i)=>{var aula=this.aulaService.getEstruturaAula();aula.turma.id=obj.turma.id;aula.dia.id=dia.id;if(!obj.turma.etapa.frequenciaUnificada){aula.disciplina.id=obj.id;aula.horario.id=horario.id}else{delete aula.disciplina;delete aula.horario}
var resultado=this.aulaService.salvar({aulas:[aula]});if(i===horarios.length-1){resultado.then(()=>{this.escolherDia(dia,horarios)})}})}else{aulas.forEach((aula)=>{aula.horario.inicio=this.util.converteHora(aula.horario.inicio)});this.aula=aulas[0];this.aulas=aulas;this.buscarAnotacoes(this.aula);this.frequenciaService.getAll({aula:this.aula.id},!0).then((alunos)=>{this.alunos=alunos;alunos.forEach((aluno)=>{this.carregarFoto(aluno.aluno.id).then((foto)=>{aluno.aluno.urlFoto=foto})})})}});this.chamada=!0}else{this.util.toast("Não há nenhum horário de aula neste dia para esta disciplina.")}}
buscarAlunos(disciplina){this.alunos=[];this.disciplinaCursadaService.getAll({disciplinaOfertada:disciplina.id,view:'medias'},!0).then((cursadas)=>{cursadas.forEach((cursada,i)=>{var frequencia=this.frequenciaService.getEstruturaFrequencia();var aluno=cursada.matricula.aluno;aluno.foto=this.util.avatarPadrao();this.carregarFoto(cursada.matricula.aluno.id).then((foto)=>{aluno.urlFoto=foto;frequencia.aluno=aluno;frequencia.aula.id=this.aula.id;this.alunos.push(frequencia)})})})}
atualizarListaFrequencia(aula){var obj=JSON.parse(sessionStorage.getItem('turmaSelecionada'));this.buscarAnotacoes(aula);this.alunos=[];this.frequenciaService.getAll({aula:aula.id},!0).then((alunos)=>{this.alunos=alunos;alunos.forEach((aluno)=>{this.carregarFoto(aluno.aluno.id).then((foto)=>{aluno.aluno.urlFoto=foto})})})}
buscarAnotacoes(aula){this.aulaService.getAnotacoes({aula:aula.id},!0).then((anotacoes)=>{this.anotacoes=anotacoes})}
salvarAnotacao(){var anotacao=this.aulaService.getEstruturaAnotacao();if(this.util.isVazio(this.conteudo)){this.util.toast("Não é possível criar anotações vazias.")}else{anotacao.aula.id=this.aula.id;anotacao.conteudo=this.conteudo;this.aulaService.salvarAnotacao(anotacao,!0).then(()=>{this.conteudo=null;this.buscarAnotacoes(this.aula)})}}
removerAnotacao(event,anotacao){var self=this;let confirm=this.util.modalExclusao(event,"Remover Anotação","Deseja remover esta anotação?",'remover',this.mdDialog);this.mdDialog.show(confirm).then(function(){let id=anotacao.id;var index=self.util.buscaIndice(id,self.anotacoes);if(index!==!1){self.aulaService.remover(anotacao,"Anotação","f");self.anotacoes.splice(index,1)}})}
carregarFoto(pessoaId){var token="Bearer "+sessionStorage.getItem('token');var fileUrl=this.erudioConfig.urlServidor+'/pessoas/'+pessoaId+'/foto';return this.http.get(fileUrl,{headers:{"JWT-Authorization":token},responseType:'arraybuffer'}).then((data)=>{return new Promise((resolve)=>{var file=new Blob([data.data],{type:'image/jpg'});resolve(URL.createObjectURL(file))})},(error)=>{return new Promise((resolve)=>{resolve(this.erudioConfig.dominio+"/apps/professor/avaliacoes/assets/images/avatar.png")})})}
fecharForm(){this.chamada=!1;this.alunos=[];this.conteudo=null}
verStatus(status){if(status==="PRESENCA"){return 'presenca-cor'}else if(status==="FALTA"){return 'falta-cor'}else{return 'falta-justificada-cor'}}
darFrequencia(frequencia,loader){if(frequencia.status==="PRESENCA"){frequencia.status="FALTA";if(!this.util.isVazio(frequencia.justificativa)){frequencia.justificativa=''}
this.frequenciaService.atualizar(frequencia,!0)}else{frequencia.status="PRESENCA";frequencia.justificativa="";$(".justificativa-aluno-"+frequencia.id).hide();this.frequenciaService.atualizar(frequencia,!0)}}
atualizarJustificativa(){if(this.alunoSelecionado.justificativa.length>0){this.alunoSelecionado.status="FALTA_JUSTIFICADA"}else{this.alunoSelecionado.status="FALTA"}
this.frequenciaService.atualizar(this.alunoSelecionado,!0).then(()=>{this.fecharPainel()})}
mostrarJustificativa(aluno){this.alunoSelecionado=aluno;$(".justificativa-aluno-"+alunoId).toggle()}
buscarEventos(){this.service.getDiasPorMes(this.calendario,this.mes+1,!0).then((dias)=>{this.dias=dias;for(var i=0;i<this.diasMes;i++){this.counterCalendario++;this.semanaCalendario.push(this.dias[i]);if(this.counterCalendario===7){this.mesCalendario.push(this.semanaCalendario);this.counterCalendario=0;this.semanaCalendario=[]}
if(i===this.diasMes-1){var dataFinal=new Date(this.ano,this.mes,i+1);this.gapFinal=6-dataFinal.getDay();for(var j=0;j<this.gapFinal;j++){this.semanaCalendario.push(null);if(j===this.gapFinal-1){this.mesCalendario.push(this.semanaCalendario)}}}}})}
linkPaginacao(){this.proximoMes=new Date(this.ano,this.mes,1);this.proximoMes.setMonth(this.proximoMes.getMonth()+1);this.mesAnterior=new Date(this.ano,this.mes,1);this.mesAnterior.setMonth(this.mesAnterior.getMonth()-1)}
classeTipoDia(dia,aulas){var classe='';if(!this.util.isVazio(dia)){if(dia.efetivo){classe+='calendario-dia-efetivo';if(aulas.length>0){return classe+' clicavel'}else{return classe}}
else if(dia.letivo){classe+='calendario-dia-letivo';return classe}
else{classe+='calendario-dia-nao-letivo';return classe}}}
paginaProxima(){this.resetCalendario();this.preparaCalendario(this.proximoMes.getMonth(),this.proximoMes.getFullYear())}
paginaAnterior(){this.resetCalendario();this.preparaCalendario(this.mesAnterior.getMonth(),this.mesAnterior.getFullYear())}
abrirPainel(index,aluno){if(aluno.status!=='PRESENCA'){this.fecharPainel();this.alunoSelecionado=aluno;$(".condensed-panel-"+index).hide();$(".expanded-panel-"+index).show()}}
fecharPainel(){$(".expanded-panel").hide();$(".condensed-panel").show()}
ultimoPainel(index,status){var classe='';if(status==="PRESENCA"){classe+="nao-clicavel"
if(this.alunos.length-1===index){return classe+' ultimo-panel'}else{return classe}}else{if(this.alunos.length-1===index){return 'ultimo-panel'}else{return ''}}}
iniciar(){let permissao=this.verificarPermissao();if(permissao){this.util.comPermissao();$('.btn-home').hide();this.attr=JSON.parse(sessionStorage.getItem('atribuicoes'));this.escrita=this.verificaEscrita();this.isAdmin=this.util.isAdmin();this.scope.$watch("shared.abaHome",(query)=>{this.fecharForm()});this.buscarCalendario();this.util.inicializar()}else{this.util.semPermissao()}}}
AulaController.$inject=["CalendarioService","Util","ErudioConfig","$timeout","TurmaService","AulaService","DiaService","QuadroHorarioService","FrequenciaService","$http","$mdDialog","$mdMenu","DisciplinaCursadaService","Shared","$scope"];angular.module('AulaController',['ngMaterial','util','erudioConfig']).controller('AulaController',AulaController)})();
(function(){class ProfAvaliacoesController{constructor(service,util,$mdDialog,erudioConfig,$timeout,baseService,etapaService,mediaService,$http,shared,$scope){this.http=$http;this.service=service;this.scope=$scope;this.baseService=baseService;this.etapaService=etapaService;this.util=util;this.mdDialog=$mdDialog;this.scope.shared=shared;this.erudioConfig=erudioConfig;this.timeout=$timeout;this.permissaoLabel="AVALIACAO";this.mediaService=mediaService;this.mediasModal=null;this.modalAberto=null;this.possuiEnturmacoes=parseInt(sessionStorage.getItem('possuiEnturmacoes'));this.mediaEmUso=null;this.avaliacaoModal=null;this.notasQualitativas=[];this.avaliacaoRemover=null;this.turmaSelecionada=null;this.dataEntrega=null;this.isQualitativa=!1;this.alunoSelecionado=null;this.tipoSistemaAvaliacao='';this.tamanhoCard=60;this.pagina=0;this.editandoNota=!1;this.avaliacaoLabel="Avaliações Cadastradas";this.listaQualitativa=!1;this.avaliacao=null;this.atribuindoNota=!1;this.editando=!1;this.mostraBotao=!1;this.disciplinaEscolhida=!1;this.iniciar()}
verificarPermissao(){return this.util.verificaPermissao(this.permissaoLabel)}
verificaEscrita(){return this.util.verificaEscrita(this.permissaoLabel)}
validarEscrita(opcao){if(opcao.validarEscrita){return this.util.validarEscrita(opcao.opcao,this.opcoes,this.escrita)}else{return!0}}
desabilitarPaginacao(){$(".fit-screen").unbind('scroll')}
tipoBotaoAdd(){if(this.disciplinasLecionadas!==undefined&&this.disciplinasLecionadas.length===1){return 'btn-add-avaliacao'}else{return 'btn-add-avaliacao-fix'}}
tipoBotaoVoltar(){if(this.disciplinasLecionadas!==undefined&&this.disciplinasLecionadas.length===1){return 'btn-voltar-avaliacao'}else{return 'btn-voltar-avaliacao-fix'}}
buscarDisciplinas(){this.isQualitativa=!1;if(!this.util.isVazio(sessionStorage.getItem('turmaSelecionada'))){this.disciplinaEscolhida=!0;this.turmaSelecionada=JSON.parse(sessionStorage.getItem('turmaSelecionada'));this.buscarAvaliacoes(!1)}}
buscarAvaliacoes(loader){this.mostraBotao=!0;this.etapaService.get(this.turmaSelecionada.turma.etapa.id,!1).then((etapa)=>{this.tipoSistemaAvaliacao=etapa.sistemaAvaliacao.regime.unidade;if(etapa.sistemaAvaliacao.tipo==="QUALITATIVO"){this.opcoes=[{tooltip:'Notas',icone:'playlist_add_check',opcao:'notas',validarEscrita:!0},];this.isQualitativa=!0;this.tamanhoCard=100;this.service.getQualitativas({page:this.pagina,disciplina:this.turmaSelecionada.id},!1).then((avaliacoes)=>{if(avaliacoes.length===0){this.msgVazio=!0}else{this.msgVazio=!1}
if(this.pagina===0){this.objetos=avaliacoes}else{if(avaliacoes.length!==0){this.objetos=this.objetos.concat(avaliacoes)}else{this.finalLista=!0;this.pagina--}}})}else{this.opcoes=[{tooltip:'Notas',icone:'playlist_add_check',opcao:'notas',validarEscrita:!0},{tooltip:'Remover',icone:'delete',opcao:'remover',validarEscrita:!0}];this.isQualitativa=!1;this.tamanhoCard=60;this.service.getQuantitativas({page:this.pagina,disciplina:this.turmaSelecionada.id},!1).then((avaliacoes)=>{if(avaliacoes.length===0){this.msgVazio=!0}else{this.msgVazio=!1}
if(this.pagina===0){this.objetos=avaliacoes}else{if(avaliacoes.length!==0){this.objetos=this.objetos.concat(avaliacoes)}else{this.finalLista=!0;this.pagina--}}});this.service.getQuantitativas({page:this.pagina,disciplina:this.turmaSelecionada.id,dataEntrega:moment().format('YYYY-MM-DD')},!1).then((avaliacoesDia)=>{if(avaliacoesDia.length===0){this.msgVazioDia=!0}else{this.msgVazioDia=!1}
this.avaliacoesDia=avaliacoesDia})}})}
buscarAvaliacoesDia(loader){if(this.isQualitativa){this.service.getQualitativas({page:this.pagina,disciplina:this.turmaSelecionada.id,dataEntrega:moment().format('YYYY-MM-DD')},loader).then((avaliacoesDia)=>{if(avaliacoesDia.length===0){this.msgVazioDia=!0}else{this.msgVazioDia=!1}
this.avaliacoesDia=avaliacoesDia})}else{this.service.getQuantitativas({page:this.pagina,disciplina:this.turmaSelecionada.id,dataEntrega:moment().format('YYYY-MM-DD')},loader).then((avaliacoesDia)=>{if(avaliacoesDia.length===0){this.msgVazioDia=!0}else{this.msgVazioDia=!1}
this.avaliacoesDia=avaliacoesDia})}}
mostraBotaoVoltar(){$('.btn-home').show();$('.btn-home').click(()=>{$('.btn-home').hide();this.fecharForm()})}
carregarAvaliacao(avaliacao){if(this.isQualitativa){this.service.getQualitativa(avaliacao.id).then((objeto)=>{this.avaliacao=objeto;this.abrirForm()})}else{this.service.getQuantitativa(avaliacao.id).then((objeto)=>{this.avaliacao=objeto;this.dataEntrega=moment(objeto.dataEntrega).format('DD/MM/YYYY');this.abrirForm()})}}
abrirPainel(index,aluno){this.fecharPainel();this.alunoSelecionado=aluno;this.buscarNotaQualitativa(aluno);$(".condensed-panel-"+index).hide();$(".expanded-panel-"+index).show()}
fecharPainel(){$(".expanded-panel").hide();$(".condensed-panel").show()}
ultimoPainel(index){if(this.mediasModal.length-1===index){return 'ultimo-panel'}else{return ''}}
abrirForm(){this.mostraBotaoVoltar();this.editando=!0;this.msgVazio=!1;this.medias=[];this.desabilitarPaginacao();this.avaliacaoLabel="Gerenciar Avaliação";if(this.isQualitativa){this.tiposQuali=this.service.getTiposAvaliacaoQuali();if(this.util.isNovo(this.avaliacao)||this.util.isVazio(this.avaliacao)){this.avaliacao=this.service.getEstruturaQualitativa()}}else{this.tamanhoCard=100;this.service.getTiposAvaliacao(null,!0).then((tiposAvaliacao)=>{this.tiposAvaliacao=tiposAvaliacao;this.medias=[];if(this.util.isNovo(this.avaliacao)||this.util.isVazio(this.avaliacao)){this.avaliacao=this.service.getEstrutura()}})}
this.etapaService.get(this.turmaSelecionada.turma.etapa.id,!0).then((etapa)=>{for(var i=0;i<etapa.sistemaAvaliacao.quantidadeMedias;i++){this.medias.push((i+1)+'º '+etapa.sistemaAvaliacao.regime.unidade)}});this.timeout(()=>{this.util.aplicarMascaras()},300)}
fecharForm(){this.avaliacaoLabel="Avaliações Cadastradas";this.atribuindoNota=!1;if(this.util.isVazio(this.objetos)){this.msgVazio=!0}this.habilitarPaginacao();this.editando=!1;this.dataEntrega=null;this.listaQualitativa=!1;if(this.isQualitativa){this.isQualitativa=!0;this.avaliacao=this.service.getEstrutura()}else{this.isQualitativa=!1;this.tamanhoCard=60;this.avaliacao=this.service.getEstruturaQualitativa()}}
validar(nomeForm){return this.util.validar(nomeForm)}
validaCampo(){this.util.validaCampo()}
salvar(nomeForm){if(this.isQualitativa){if(!this.util.isVazio(this.avaliacao.nome)&&!this.util.isVazio(this.avaliacao.media)&&!this.util.isVazio(this.avaliacao.tipo)){this.avaliacao.disciplina.id=this.turmaSelecionada.id;this.avaliacao.media=parseInt(this.avaliacao.media);delete this.avaliacao.dataEntrega;var resultado=null;delete this.avaliacao.habilidades;if(this.util.isNovoObjeto(this.avaliacao)){resultado=this.service.salvarAvaliacaoQuali(this.avaliacao,!1,!0)}else{resultado=this.service.atualizar(this.avaliacao)}
resultado.then(()=>{this.editando=!1;this.buscarAvaliacoes(!0);this.fecharForm()},(error)=>{this.util.toast(error.data.error.message)})}else{this.util.toast("Certifique que todos os campos foram preenchidos")}}else{if(!this.util.isVazio(this.avaliacao.nome)&&!this.util.isVazio(this.avaliacao.media)&&!this.util.isVazio(this.avaliacao.tipo.id)&&!this.util.isVazio(this.dataEntrega)){this.avaliacao.disciplina.id=this.turmaSelecionada.id;this.avaliacao.dataEntrega=moment(this.util.converteData(this.dataEntrega)).format('YYYY-MM-DD\T00:00:00P');this.avaliacao.media=parseInt(this.avaliacao.media);var resultado=null;delete this.avaliacao.habilidades;if(this.util.isNovoObjeto(this.avaliacao)){resultado=this.service.salvarAvaliacaoQuanti(this.avaliacao,!1,!0)}else{resultado=this.service.atualizar(this.avaliacao,!0)}
resultado.then(()=>{this.editando=!1;this.buscarAvaliacoes(!0);this.fecharForm()})}else{this.util.toast("Certifique que todos os campos foram preenchidos")}}}
paginar(){this.pagina++;this.buscarAvaliacoes(!0)}
executarOpcao(event,opcao,objeto){this.avaliacaoRemover=objeto;switch(opcao.opcao){case 'remover':this.modalExclusao(event);break;case 'notas':this.darNotas(objeto);break;default:return!1;break}}
modalExclusao(event){var self=this;let confirm=this.util.modalExclusao(event,"Remover Avaliação","Deseja remover esta avaliação?",'remover',this.mdDialog);this.mdDialog.show(confirm).then(function(){let id=self.avaliacaoRemover.id;var index=self.util.buscaIndice(id,self.objetos);if(index!==!1){self.service.remover(self.avaliacaoRemover,"Avaliação","f");self.objetos.splice(index,1);if(self.objetos.length===0){self.msgVazio=!0}self.buscarAvaliacoesDia()}})}
paddingAccordion(){if(this.isQualitativa){return 'no-padding'}else{return ''}}
buscarNotaQualitativa(media){this.service.getNotasQualitativas({avaliacao:this.avaliacaoRemover.id,media:media.id}).then((notas)=>{this.notasAvaliadas=[];this.notasQualitativas=notas;if(notas.length>0){this.editandoNota=!0}else{this.editandoNota=!1}
notas.forEach((nota)=>{nota.habilidadesAvaliadas.forEach((habilidade)=>{this.notasAvaliadas.push(habilidade.conceito.id)})})})}
darNotas(objeto,loader){this.mostraBotaoVoltar();var self=this;this.desabilitarPaginacao();this.listaQualitativa=!0;this.atribuindoNota=!0;this.mediaService.getAll({disciplinaOfertada:this.turmaSelecionada.id,numero:this.avaliacaoRemover.media},loader).then((medias)=>{this.mediasModal=medias;this.avaliacaoModal=this.avaliacaoRemover;medias.forEach((media)=>{this.carregarFoto(media.disciplinaCursada.matricula.idAluno).then((foto)=>{media.urlFoto=foto})});if(this.isQualitativa){this.mediaEmUso=objeto;this.service.getConceitos(null).then((conceitos)=>{this.conceitos=conceitos;this.service.getHabilidades({disciplina:this.turmaSelecionada.disciplinaId,media:this.avaliacaoRemover.media}).then((habilidades)=>{this.habilidades=habilidades})})}else{this.service.getNotasQuantitativas({avaliacao:objeto.id},!0).then((notas)=>{if(notas.length>0){this.editandoNota=!0;this.notasAvaliacao=notas;medias.forEach((media,index)=>{notas.forEach((nota)=>{if(nota.media.id===media.id){media.nota=nota.valor;media.temValor=!0}})})}else{this.editandoNota=!1}})}})}
carregarFoto(pessoaId){var token="Bearer "+sessionStorage.getItem('token');var fileUrl=this.erudioConfig.urlServidor+'/pessoas/'+pessoaId+'/foto';return this.http.get(fileUrl,{headers:{"JWT-Authorization":token},responseType:'arraybuffer'}).then((data)=>{return new Promise((resolve)=>{var file=new Blob([data.data],{type:'image/jpg'});resolve(URL.createObjectURL(file))})},(error)=>{return new Promise((resolve)=>{resolve(this.erudioConfig.dominio+"/apps/professor/avaliacoes/assets/images/avatar.png")})})}
isNotaSalva(aluno){if(!this.util.isVazio(aluno.temValor)){return 'isNotaSalva'}else{return 'isNotaNova'}}
salvarNotasQualitativas(){var nota=this.service.getEstruturaNotaQualitativa();var self=this;var tamanho=$('md-select.conceitos').length;var preenchidos=$("md-select.conceitos md-select-value span div.md-text").length;if(tamanho-preenchidos===0){if(this.notasQualitativas.length>0){angular.forEach(angular.element('md-select.conceitos md-select-value span div.md-text'),(value,key)=>{var conceito={id:null};var element=angular.element(value);var valueText=element[0].textContent;self.conceitos.forEach((conceito)=>{if(valueText===conceito.sigla){conceito.id=conceito.id;if(this.notasQualitativas[0].habilidadesAvaliadas[key]!==undefined){this.notasQualitativas[0].habilidadesAvaliadas[key].conceito=conceito}
if(tamanho-1===key){if(this.notasQualitativas[0].avaliacao.disciplina.professores!==undefined){delete this.notasQualitativas[0].avaliacao.disciplina.professores}
var result=this.service.atualizar(this.notasQualitativas[0],!0,!0);result.then((resultado)=>{this.notasQualitativas[0]=resultado})}}})})}else{angular.forEach(angular.element('md-select.conceitos md-select-value span div.md-text'),(value,key)=>{var habilidade={habilidade:{id:null},conceito:{id:null}};var element=angular.element(value);var media=$('#modal-qualitativa').attr('data-media');var valueText=element[0].textContent;nota.avaliacao.id=self.avaliacaoRemover.id;nota.media.id=media;self.conceitos.forEach((conceito)=>{if(valueText===conceito.sigla){habilidade.conceito.id=conceito.id;if(self.habilidades[key]!==undefined){habilidade.habilidade.id=self.habilidades[key].id;nota.habilidadesAvaliadas.push(habilidade)}
if(tamanho-1===key){this.service.salvarQualitativa(nota).then((resultado)=>{this.notasQualitativas[0]=resultado})}}})})}}else{this.util.toast("Por favor, verifique se todos os itens foram preenchidos.")}}
salvarNotasQuantitativas(){let tamanho=$('.formNotas').length;let contador=0;$('.formNotas').each((index,element)=>{var input=$(element).find('input');if(input.val()===undefined||input.val()===null||input.val()===''){contador++}
if(index===tamanho-1){if(contador>0){$scope.util.toast('O sistema irá salvar, mas há notas não preenchidas.')}}});if(this.editandoNota){var notasSalvas=$('.formNotas').find('input.isNotaSalva');var notasNovas=$('.formNotas').find('input.isNotaNova');for(var i=0;i<notasSalvas.length;i++){var objeto=null;var mediaId=$(notasSalvas[i]).attr('data-media');this.notasAvaliacao.forEach((nota,j)=>{if(nota.media.id===parseInt(mediaId)){objeto=nota;var value=$(notasSalvas[i]).val();if(!this.util.isVazio(value)){objeto.valor=parseFloat(value);this.service.atualizar(objeto,!1);if(i===notasSalvas.length-1){this.util.toast("Notas atualizadas com sucesso.")}}}})}
for(var j=0;j<notasNovas.length;j++){var objeto=null;var mediaId=$(notasNovas[j]).attr('data-media');var valor=$(notasNovas[j]).val();this.salvarNotaQuanti(objeto,mediaId,valor);if(j===notasNovas.length-1){this.util.toast("Notas salvas com sucesso.")}}}else{var notasNovas=$('.formNotas').find('input.isNotaNova');for(var j=0;j<notasNovas.length;j++){var objeto=null;var mediaId=$(notasNovas[j]).attr('data-media');var valor=$(notasNovas[j]).val();$(notasNovas[j]).removeClass('isNotaNova');$(notasNovas[j]).addClass('isNotaSalva');this.salvarNotaQuanti(objeto,mediaId,valor);if(j===notasNovas.length-1){this.util.toast("Notas salvas com sucesso.")}}}}
salvarNotaQuanti(objeto,mediaId,valor){objeto=this.service.getEstruturaQuantitativa();objeto.media={id:mediaId};objeto.avaliacao={id:this.avaliacaoModal.id};if(valor!==undefined&&valor!==null&&valor!==''){objeto.valor=parseFloat(valor);this.service.salvarQuantitativa(objeto,!1).then((obj)=>{this.notasAvaliacao.push(obj)})}}
habilitarPaginacao(){this.timeout(function(){$(".fit-screen").scroll(function(){let distancia=Math.floor(Number($(".conteudo").offset().top-$(document).height()));let altura=Math.floor(Number($(".main-layout").height()));let total=altura+distancia;var active=$("#avaliacoesHome").parent().parent().parent().parent().hasClass('md-active');if(total===0&&active){self.paginar()}})},500)}
abrirNotaRemota(query){var avaliacao=this.scope.shared.getAvaliacao();if(!this.util.isVazio(query)){this.executarOpcao(null,{opcao:'notas'},avaliacao)}};iniciar(){let permissao=this.verificarPermissao();let self=this;$('.btn-home').hide();if(permissao){this.util.comPermissao();this.escrita=this.verificaEscrita();this.fab={tooltip:'Adicionar Avaliação',icone:'add',href:this.link+'novo'};this.scope.$watch("shared.avaliacaoAbrir.id",(query)=>{this.abrirNotaRemota(query)});this.scope.$watch("shared.abaHome",(query)=>{this.fecharForm()});this.timeout(()=>{this.validaCampo()},500);this.habilitarPaginacao();this.buscarDisciplinas();this.util.inicializar()}else{this.util.semPermissao()}}}
ProfAvaliacoesController.$inject=["AvaliacaoService","Util","$mdDialog","ErudioConfig","$timeout","BaseService","EtapaService","MediaService","$http","Shared","$scope"];angular.module('ProfAvaliacoesController',['ngMaterial','util','erudioConfig']).controller('ProfAvaliacoesController',ProfAvaliacoesController)})();
(function(){class EventoHomeController{constructor(service,util,erudioConfig,routeParams,$timeout,$mdDialog,$mdMenu,turmaService){this.service=service;this.util=util;this.routeParams=routeParams;this.erudioConfig=erudioConfig;this.timeout=$timeout;this.turmaService=turmaService;this.mdDialog=$mdDialog;this.mdMenu=$mdMenu;this.calendario=null;this.mesCalendario=[];this.semanaCalendario=[];this.permissaoLabel="HOME_PROFESSOR";this.linkModulo="/#!/calendarios/";this.nomeForm="calendarioForm";this.mes=null;this.ano=null;this.disciplinaEscolhida=!1;this.possuiEnturmacoes=parseInt(sessionStorage.getItem('possuiEnturmacoes'));this.iniciar()}
verificarPermissao(){return this.util.verificaPermissao(this.permissaoLabel)}
verificaEscrita(){return this.util.verificaEscrita(this.permissaoLabel)}
validarEscrita(opcao){if(opcao.validarEscrita){return this.util.validarEscrita(opcao.opcao,this.opcoes,this.escrita)}else{return!0}}
resetCalendario(){this.mesCalendario=[];this.semanaCalendario=[]}
preparaCalendario(mes,ano){var self=this;if(this.util.isVazio(mes)&&this.util.isVazio(ano)){var dateBase=new Date();this.mes=dateBase.getMonth();this.ano=dateBase.getFullYear();this.preparaCalendario(this.mes,this.ano)}else{this.diaS=1;this.mes=mes;this.ano=ano;this.diaSemana=new Date(this.ano,this.mes,this.diaS).getDay();this.counterCalendario=this.diaSemana;this.gapInicio=this.diaSemana;this.diasMes=this.util.diasNoMes(this.mes,this.ano);this.semanaCalendario=new Array(this.gapInicio);this.nomeMes=this.util.nomeMes(this.mes);this.timeout(function(){self.linkPaginacao()},500);self.buscarEventos()}};buscarCalendario(){if(!this.util.isVazio(sessionStorage.getItem('turmaSelecionada'))){this.disciplinaEscolhida=!0;var self=this;var obj=JSON.parse(sessionStorage.getItem('turmaSelecionada'));this.turmaService.get(obj.turma.id,!0).then((turma)=>{this.calendario=turma.calendario;this.preparaCalendario()})}}
abrirDia(dia){this.dia=dia;var self=this;this.mdDialog.show({locals:{dia:{dia:dia,config:this.erudioConfig}},controller:this.modalControl,templateUrl:this.erudioConfig.dominio+'/apps/professor/eventos/partials/dia.html',parent:angular.element(document.body),targetEvent:event,clickOutsideToClose:!0})}
modalControl($scope,dia){$scope.dia=dia.dia;$scope.config=dia.config;$scope.dia.eventos.forEach((evento)=>{let ini=evento.inicio.split(":");evento.inicio=ini[0]+":"+ini[1];let termino=evento.termino.split(":");evento.termino=termino[0]+":"+termino[1]});$scope.abreMenu=function($mdMenu,ev){var origemEv=ev;$mdMenu.open(ev)}}
buscarEventos(){this.service.getDiasPorMes(this.calendario,this.mes+1,!0).then((dias)=>{this.dias=dias;for(var i=0;i<this.diasMes;i++){this.counterCalendario++;this.semanaCalendario.push(this.dias[i]);if(this.counterCalendario===7){this.mesCalendario.push(this.semanaCalendario);this.counterCalendario=0;this.semanaCalendario=[]}
if(i===this.diasMes-1){var dataFinal=new Date(this.ano,this.mes,i+1);this.gapFinal=6-dataFinal.getDay();for(var j=0;j<this.gapFinal;j++){this.semanaCalendario.push(null);if(j===this.gapFinal-1){this.mesCalendario.push(this.semanaCalendario)}}}}})}
linkPaginacao(){this.proximoMes=new Date(this.ano,this.mes,1);this.proximoMes.setMonth(this.proximoMes.getMonth()+1);this.mesAnterior=new Date(this.ano,this.mes,1);this.mesAnterior.setMonth(this.mesAnterior.getMonth()-1)}
classeTipoDia(dia){if(!this.util.isVazio(dia)){if(dia.efetivo){return 'calendario-dia-efetivo'}else if(dia.letivo){return 'calendario-dia-letivo'}else{return 'calendario-dia-nao-letivo'}}}
paginaProxima(){this.resetCalendario();this.preparaCalendario(this.proximoMes.getMonth(),this.proximoMes.getFullYear())}
paginaAnterior(){this.resetCalendario();this.preparaCalendario(this.mesAnterior.getMonth(),this.mesAnterior.getFullYear())}
iniciar(){let permissao=this.verificarPermissao();if(permissao){this.fab={tooltip:'Voltar à lista',icone:'arrow_back',href:this.erudioConfig.dominio+this.linkModulo};this.util.comPermissao();this.attr=JSON.parse(sessionStorage.getItem('atribuicoes'));this.util.setTitulo(this.titulo);this.escrita=this.verificaEscrita();this.isAdmin=this.util.isAdmin();this.buscarCalendario();this.util.inicializar()}else{this.util.semPermissao()}}}
EventoHomeController.$inject=["CalendarioService","Util","ErudioConfig","$routeParams","$timeout","$mdDialog","$mdMenu","TurmaService"];angular.module('EventoHomeController',['ngMaterial','util','erudioConfig']).controller('EventoHomeController',EventoHomeController)})();
(function(){class MediaController{constructor(service,util,erudioConfig,$timeout,$mdDialog,disciplinaCursadaService,avaliacaoService,etapaService,$http,mediaService,disciplinaOfertadaService,shared){this.service=service;this.util=util;this.shared=shared;this.disciplinaEscolhida=!1;this.erudioConfig=erudioConfig;this.http=$http;this.mediaService=mediaService;this.disciplina=JSON.parse(sessionStorage.getItem('turmaSelecionada'));this.permissaoLabel="AVALIACAO";this.disciplinaCursadaService=disciplinaCursadaService;this.mdDialog=$mdDialog;this.medias=[];this.headers=[];this.cursadas=[];this.etapaService=etapaService;this.avaliacaoService=avaliacaoService;this.isQualitativa=!1;this.parciais=[];this.disciplinaOfertadaService=disciplinaOfertadaService;this.possuiEnturmacoes=parseInt(sessionStorage.getItem('possuiEnturmacoes'));this.iniciar()}
verificarPermissao(){return this.util.verificaPermissao(this.permissaoLabel)}
verificaEscrita(){return this.util.verificaEscrita(this.permissaoLabel)}
validarEscrita(opcao){if(opcao.validarEscrita){return this.util.validarEscrita(opcao.opcao,this.opcoes,this.escrita)}else{return!0}}
buscarAlunos(reiniciar,media){if(!this.util.isVazio(sessionStorage.getItem('turmaSelecionada'))){this.disciplinaEscolhida=!0;if(reiniciar){this.medias=[];this.cursadas=[]}
this.etapaService.get(this.disciplina.turma.etapa.id,!1).then((etapa)=>{if(etapa.sistemaAvaliacao.tipo==="QUALITATIVO"){this.isQualitativa=!0}else{this.isQualitativa=!1}});this.disciplinaCursadaService.getAll({disciplinaOfertada:this.disciplina.id,view:'medias'},!0).then((cursadas)=>{this.cursadas=cursadas;cursadas.forEach((cursada,i)=>{if(i===0){var medias=[];cursada.medias.forEach((media,j)=>{this.headers.push("M"+(j+1));this.headers.push('Frequência')})}
if(media!==undefined){cursada.medias.forEach((mediaObj)=>{if(mediaObj.id===media.id){this.buscarNotaIndividual(mediaObj)}})}
cursada.matricula.aluno.foto=this.util.avatarPadrao();this.carregarFoto(cursada.matricula.aluno.id).then((foto)=>{cursada.matricula.aluno.foto=foto})})})}}
carregarFoto(pessoaId){var token="Bearer "+sessionStorage.getItem('token');var fileUrl=this.erudioConfig.urlServidor+'/pessoas/'+pessoaId+'/foto';return this.http.get(fileUrl,{headers:{"JWT-Authorization":token},responseType:'arraybuffer'}).then((data)=>{return new Promise((resolve)=>{var file=new Blob([data.data],{type:'image/jpg'});resolve(URL.createObjectURL(file))})},(error)=>{return new Promise((resolve)=>{resolve(this.erudioConfig.dominio+"/apps/professor/avaliacoes/assets/images/avatar.png")})})}
buscarNotaIndividual(media){if(this.isQualitativa){this.avaliacaoService.getNotasQualitativas({media:media.id}).then((parciais)=>{media.parciais=parciais})}else{this.avaliacaoService.getNotasQuantitativas({media:media.id}).then((parciais)=>{media.parciais=parciais})}}
abrirPainel(index,medias){this.fecharPainel();$(".condensed-panel-"+index).hide();$(".expanded-panel-"+index).show();this.parciais=[];medias.forEach((media)=>{this.buscarNotaIndividual(media),!1})}
fecharPainel(){$(".expanded-panel").hide();$(".condensed-panel").show()}
ultimoPainel(index){if(this.cursadas.length-1===index){return 'ultimo-panel'}else{return ''}}
calcularMedia(media,$index){this.mediaService.get(media.id,!0).then((mediaObj)=>{delete mediaObj.valor;mediaObj.disciplinaCursada={id:mediaObj.disciplinaCursada.id};delete mediaObj.faltas;this.mediaService.atualizar(mediaObj).then((mediaCalculada)=>{this.buscarAlunos(!1,mediaCalculada)})})}
redirectAvaliacao(avaliacao){this.shared.setAvaliacao(avaliacao);var self=this;angular.forEach(angular.element(".md-tab"),(val,key)=>{if($(val).text()==='avaliações'){setTimeout(()=>{$(val).trigger('click')},10)}})}
calcularMediaFinal(){let confirm=this.util.customDialog(event,"Média Final","Deseja realmente calcular a média final?",'calcular',this.mdDialog);this.mdDialog.show(confirm).then(()=>{this.disciplinaOfertadaService.fecharMediaFinal(this.disciplina).then(()=>{this.buscarAlunos(!0)},()=>{this.util.toast('Preencha todas as médias antes de calcular a média final.')})})}
iniciar(){let permissao=this.verificarPermissao();if(permissao){this.fab={tooltip:'Voltar à lista',icone:'arrow_back'};this.util.comPermissao();this.attr=JSON.parse(sessionStorage.getItem('atribuicoes'));this.escrita=this.verificaEscrita();this.isAdmin=this.util.isAdmin();this.buscarAlunos(!0);this.util.inicializar()}else{this.util.semPermissao()}}}
MediaController.$inject=["CalendarioService","Util","ErudioConfig","$timeout","$mdDialog","DisciplinaCursadaService","AvaliacaoService","EtapaService","$http","MediaService","DisciplinaOfertadaService","Shared"];angular.module('MediaController',['ngMaterial','util','erudioConfig']).controller('MediaController',MediaController)})();
(function(){class PerfilController{constructor(service,util,erudioConfig,routeParams,$timeout,estadoService,cidadeService,enderecoService,telefoneService,$scope,beneficioService,necessidadeEspecialService,usuarioService,$http){this.service=service;this.http=$http;this.scope=$scope;this.util=util;this.routeParams=routeParams;this.erudioConfig=erudioConfig;this.enderecoService=enderecoService;this.estadoService=estadoService;this.cidadeService=cidadeService;this.telefoneService=telefoneService;this.beneficioService=beneficioService;this.necessidadeEspecialService=necessidadeEspecialService;this.usuarioService=usuarioService;this.telefones=[];this.nomeCidade='';this.cidade=null;this.estados=[];this.etnias=[];this.nacionalidades=["BRASILEIRO","ESTRANGEIRO","ESTRANGEIRO_NATURALIZADO"];this.nomeNaturalidade="";this.estadosCivis=[];this.filiacoes=["Não se aplica","Filiação 1","Filiação 2","Outro"];this.tipoCertidao=null;this.termo=null;this.livro=null;this.folha=null;this.responsavel=null;this.particularidades=[];this.cpfAtual=null;this.particularidadesSelecionadas=[];this.necessidades=[];this.necessidadesSelecionadas=[];this.beneficios=[];this.beneficiosSelecionados=[];this.senha=null;this.novaSenha=null;this.timeout=$timeout;this.scope.perfil=null;this.permissaoLabel="";this.titulo="";this.linkModulo="/#!";this.nomeForm="perfilForm";this.tiposTelefone=['CELULAR','COMERCIAL','RESIDENCIAL'];this.mapa={};this.abaAtiva=0;this.temFoto=!1;this.fotoSrc=null;this.iniciar()}
verificarPermissao(){return this.util.verificaPermissao(this.permissaoLabel)}
verificaEscrita(){return this.util.verificaEscrita(this.permissaoLabel)}
validarEscrita(opcao){if(opcao.validarEscrita){return this.util.validarEscrita(opcao.opcao,this.opcoes,this.escrita)}else{return!0}}
preparaForm(){this.fab={tooltip:'Voltar à lista',icone:'arrow_back',href:this.erudioConfig.dominio+this.linkModulo};this.form=this.util.getInputBlockCustom('perfil','form','professor');this.formCards=[{label:'Foto',href:this.util.getInputBlockCustom('perfil','foto','professor')},{label:'Informações Pessoais',href:this.util.getInputBlockCustom('perfil','informacoesPessoais','professor')},{label:'Contatos',href:this.util.getInputBlockCustom('perfil','contatos','professor')},{label:'Endereço',href:this.util.getInputBlockCustom('perfil','endereco','professor')}];this.formCardsDocumentos=[{label:'Documentos',href:this.util.getInputBlockCustom('perfil','documentos','professor')},{label:'Particularidades',href:this.util.getInputBlockCustom('perfil','particularidades','professor')}];this.formCardsUsuario=[{label:'Usuário',href:this.util.getInputBlockCustom('perfil','usuario','professor')},];this.forms=[{nome:this.nomeForm,formCards:this.formCards},{nome:this.nomeForm,formCards:this.formCardsDocumentos},{nome:this.nomeForm,formCards:this.formCardsUsuario}]}
abreArquivo(){$("#foto-perfil").trigger('click')}
mostraCameraStream(){$(".cortina-foto").show();var video=document.querySelector('#camera-stream');navigator.getMedia=(navigator.getUserMedia||navigator.webkitGetUserMedia||navigator.mozGetUserMedia||navigator.msGetUserMedia);if(!navigator.getMedia){this.util.toast("Seu navegador ainda não possui suporte para tirar fotos.")}else{navigator.getMedia({video:!0},(stream)=>{video.src=window.URL.createObjectURL(stream);$('.start-video').show();video.play()},(error)=>{console.log(error)})}}
capturar(){var imageW=$('#camera-stream').width();var imageH=$('#camera-stream').height();var foto=this.tirarFoto();var image=document.querySelector("#foto-perfil-preview");image.setAttribute('src',foto);image.classList.add('visivel');image.setAttribute('style','width:'+imageW+'px; height:'+imageH+'px;');this.temFoto=!0}
tirarFoto(){var video=document.querySelector('#camera-stream');var hidden_canvas=document.querySelector('canvas');var context=hidden_canvas.getContext('2d');var width=video.videoWidth;var height=video.videoHeight;if(width&&height){hidden_canvas.width=width;hidden_canvas.height=height;context.drawImage(video,0,0,width,height);return hidden_canvas.toDataURL('image/jpeg')}}
removerPreFoto(){var image=document.querySelector("#foto-perfil-preview");image.setAttribute('src',"");image.classList.remove('visivel');this.temFoto=!1}
salvarFoto(){var src=$("#foto-perfil-preview").attr('src');var image=document.querySelector("#foto-perfil-preview");this.fotoSrc=src;var token="Bearer "+sessionStorage.getItem('token');var fileUrl=this.erudioConfig.urlServidor+'/pessoas/'+this.scope.pessoa.id+'/foto';if(!this.util.isVazio(src)){var file=this.util.dataURLtoFile(src,'avatar_'+this.scope.pessoa.id+'.jpg');var fd=new FormData();fd.append('foto',file);this.timeout(()=>{this.http.post(fileUrl,fd,{headers:{"JWT-Authorization":token,'Content-type':undefined}}).then(()=>{$('.foto-professor img').attr('src',src)})},500)}
this.cancelarFoto()}
cancelarFoto(){var image=document.querySelector("#foto-perfil-preview");var video=document.querySelector('#camera-stream');video.src="";image.setAttribute('src',"");image.classList.remove('visivel');this.temFoto=!1;$('.start-video').hide();$(".cortina-foto").hide()}
salvarFotoUpload(){this.timeout(()=>{var input=document.getElementById('foto-perfil');var atribuicoes=JSON.parse(sessionStorage.getItem('atribuicoes'));var token="Bearer "+sessionStorage.getItem('token');var file=input.files[0];var fileUrl=this.erudioConfig.urlServidor+'/pessoas/'+atribuicoes.pessoa.id+'/foto';var fd=new FormData();fd.append('foto',file);this.http.post(fileUrl,fd,{headers:{"JWT-Authorization":token,'Content-type':undefined}}).then(()=>{this.timeout(()=>{this.recarregarFoto().then((foto)=>{$('.foto-professor img').attr('src',foto)})},500)})},500)}
recarregarFoto(){var atribuicoes=JSON.parse(sessionStorage.getItem('atribuicoes'));var token="Bearer "+sessionStorage.getItem('token');var fileUrl=this.erudioConfig.urlServidor+'/pessoas/'+atribuicoes.pessoa.id+'/foto';return this.http.get(fileUrl,{headers:{"JWT-Authorization":token},responseType:'arraybuffer'}).then((data)=>{return new Promise((resolve)=>{var file=new Blob([data.data],{type:'image/jpg'});resolve(URL.createObjectURL(file))})},(error)=>{return new Promise((resolve)=>{resolve(this.erudioConfig.dominio+"/apps/professor/avaliacoes/assets/images/avatar.png")})})};verificarEstado(estadoId){if(!this.util.isVazio(estadoId)){var retorno=!1;this.estados.forEach((estado)=>{if(estado.id===estadoId){retorno=!0}});return retorno}}
getPasso(index){this.abaAtiva=index;$('.step-tab').hide();$('.step-tab-'+index).show()}
buscarPessoa(){var self=this;var pessoaId=JSON.parse(sessionStorage.getItem('atribuicoes')).pessoa.id;this.scope.pessoa=this.service.getEstrutura();this.senha=null;this.novaSenha=null;this.scope.telefone=this.service.getEstruturaTelefone();this.tipoCertidao=null;this.termo=null;this.livro=null;this.folha=null;this.service.get(pessoaId).then((pessoa)=>{this.scope.pessoa=pessoa;this.cpfAtual=this.scope.pessoa.cpfCnpj;if(this.scope.pessoa.naturalidade!==undefined){this.nomeNaturalidade=this.scope.pessoa.naturalidade.nome+' - '+this.scope.pessoa.naturalidade.estado.sigla}
this.scope.pessoa.dataNascimento=this.util.formataData(this.scope.pessoa.dataNascimento);if(this.scope.pessoa.dataExpedicaoRg!==undefined){this.scope.pessoa.dataExpedicaoRg=this.util.formataData(this.scope.pessoa.dataExpedicaoRg)}
if(this.scope.pessoa.dataExpedicaoCertidaoNascimento!==undefined){this.scope.pessoa.dataExpedicaoCertidaoNascimento=this.util.formataData(this.scope.pessoa.dataExpedicaoCertidaoNascimento)}
this.formatarCertidao();if(this.scope.pessoa.responsavelNome===this.scope.pessoa.nomeMae){this.responsavel="Filiação 1"}else if(this.scope.pessoa.responsavelNome===this.scope.pessoa.nomePai){this.responsavel="Filiação 2"}else if(this.scope.pessoa.responsavelNome==="nenhum"){this.responsavel="Não se aplica"}
else{this.responsavel="Outro"}
this.buscarEtnias();this.buscarEstadosCivis();this.buscarParticularidades();this.carregarParticularidades();this.buscarNecessidades();this.buscarBeneficios();this.carregarNecessidades();this.carregarBeneficios();this.buscarEstados().then((estados)=>this.estados=estados);if(this.scope.pessoa.telefones.length>0){this.getTelefones(this.scope.pessoa.telefones)}
if(!this.util.isVazio(this.scope.pessoa.endereco)){this.getEndereco(this.scope.pessoa.endereco.id)}
this.getPasso(0);$('#foto-perfil').change(()=>{this.salvarFotoUpload()});this.util.aplicarMascaras()})}
carregarParticularidades(){this.particularidadesSelecionadas=[];if(this.scope.pessoa.particularidades.length>0){this.scope.pessoa.particularidades.forEach((particularidade)=>{this.particularidadesSelecionadas.push(particularidade.id)})}}
carregarNecessidades(){this.necessidadesSelecionadas=[];if(this.scope.pessoa.necessidadesEspeciais.length>0){this.scope.pessoa.necessidadesEspeciais.forEach((necessidade)=>{this.necessidadesSelecionadas.push(necessidade.id)})}}
carregarBeneficios(){this.beneficiosSelecionados=[];if(this.scope.pessoa.beneficiosSociais.length>0){this.scope.pessoa.beneficiosSociais.forEach((beneficio)=>{this.beneficiosSelecionados.push(beneficio.id)})}}
formatarCertidao(){if(this.scope.pessoa.certidaoNascimento){if(this.scope.pessoa.certidaoNascimento.indexOf("00000000000000000")!==-1){this.tipoCertidao="certidao-antiga";var certidao=this.scope.pessoa.certidaoNascimento.replace("00000000000000000","");this.livro=certidao.toString().slice(0,5);this.folha=certidao.toString().slice(5,8);this.termo=certidao.toString().slice(8,15)}else{this.tipoCertidao="certidao"}}}
buscarEtnias(){this.service.getRacas(null,!0).then((etnias)=>{this.etnias=etnias})}
buscarEstadosCivis(){this.service.getEstadosCivis(null,!0).then((estadosCivis)=>{this.estadosCivis=estadosCivis})}
buscarParticularidades(){this.service.getParticularidades(null,!0).then((particularidades)=>{this.particularidades=particularidades})}
buscarNecessidades(){this.necessidadeEspecialService.getAll(null,!0).then((necessidades)=>{this.necessidades=necessidades})}
buscarBeneficios(){this.beneficioService.getAll(null,!0).then((beneficios)=>{this.beneficios=beneficios})}
buscarEstados(){return this.estadoService.getAll(null,!0)}
buscarCidades(query,pessoa){if(query.length>2){var self=this;if(pessoa.endereco.cidade.estado.id===null){return[{id:null,nome:'É necessário selecionar um estado.'}]}else{return this.cidadeService.getAll({estado:pessoa.endereco.cidade.estado.id,nome:query},!0)}}}
buscarCidadesNaturalidade(query){if(query.length>2){return this.cidadeService.getAll({nome:query},!0)}}
getEndereco(id){var self=this;this.service.getEnderecoCompleto(id,!0).then((endereco)=>{this.scope.pessoa.endereco=endereco;this.timeout(()=>{this.initMapa()},1000);this.cidadeService.get(this.scope.pessoa.endereco.cidade.id).then((cidade)=>{this.cidade=cidade;this.scope.pessoa.endereco.cidade=this.cidade;this.buscarEstados().then((estados)=>{this.estados=estados;this.timeout(()=>{this.util.validarCampos()},1000)})})})}
getTelefones(telefones){var self=this;if(telefones.length>0){$('md-divider.hide').show();$('.md-subheader.hide').show();for(var i=0;i<telefones.length;i++){this.telefoneService.get(telefones[i].id,!0).then((telefone)=>{this.telefones.push(telefone)})}}else{$('md-divider.hide').hide();$('.md-subheader.hide').hide()}}
validaCampo(){this.util.validaCampo()}
validar(){var obrigatorios=this.util.validar(this.nomeForm);if(this.cidade.id===null){obrigatorios=!1}
if(this.scope.pessoa.certidaoNascimento.length>0&&this.scope.pessoa.certidaoNascimento.length<32){this.util.toast("Certidão de Nascimento deve ter 32 dígitos.");return!1}
if(obrigatorios){return!0}else{return!1}}
salvar(){if(this.validar()){this.scope.pessoa.particularidades=[];this.scope.pessoa.necessidadesEspeciais=[];this.scope.pessoa.beneficiosSociais=[];this.particularidadesSelecionadas.forEach((particularidade)=>{this.scope.pessoa.particularidades.push({id:particularidade})});this.necessidadesSelecionadas.forEach((necessidade)=>{this.scope.pessoa.necessidadesEspeciais.push({id:necessidade})});this.beneficiosSelecionados.forEach((beneficio)=>{this.scope.pessoa.beneficiosSociais.push({id:beneficio})});this.scope.pessoa.endereco.cidade.id=this.cidade.id;var resultado=null;this.scope.pessoa.dataNascimento=this.util.converteData(this.scope.pessoa.dataNascimento);this.scope.pessoa.estadoCivil={id:this.scope.pessoa.estadoCivil.id};this.scope.pessoa.raca={id:this.scope.pessoa.raca.id};if(!this.util.isVazio(this.scope.pessoa.naturalidade)){this.scope.pessoa.naturalidade={id:this.scope.pessoa.naturalidade.id}}
if(!this.util.isVazio(this.scope.pessoa.dataExpedicaoRg)){this.scope.pessoa.dataExpedicaoRg=this.util.converteData(this.scope.pessoa.dataExpedicaoRg)}
if(!this.util.isVazio(this.scope.pessoa.dataExpedicaoCertidaoNascimento)){this.scope.pessoa.dataExpedicaoCertidaoNascimento=this.util.converteData(this.scope.pessoa.dataExpedicaoCertidaoNascimento)}
if(this.tipoCertidao==="certidao-antiga"){this.scope.pessoa.certidaoNascimento=this.livro+this.folha+this.termo+"00000000000000000"}
resultado=this.service.atualizar(this.scope.pessoa,!0);resultado.then(()=>{this.util.redirect(this.erudioConfig.dominio+this.linkModulo)},(erro)=>{this.util.toast(erro.data.error.message)})}}
atualizarUsuario(){this.usuarioService.get(this.scope.pessoa.usuario.id).then((usuario)=>{usuario.username=this.scope.pessoa.cpfCnpj;this.usuarioService.atualizar(usuario,!0).then(()=>{sessionStorage.removeItem('username');sessionStorage.setItem('username',this.scope.pessoa.cpfCnpj);this.timeout(()=>{this.util.redirect(this.erudioConfig.dominio+this.linkModulo)},500)})})}
adicionarTelefone(){var self=this;var tamanhoTelefone=this.scope.telefone.numero.length;if(!this.util.isVazio(this.scope.telefone.numero)&&!this.util.isVazio(this.scope.telefone.descricao)){this.telefones.push(this.scope.telefone);$('md-divider.hide').show();$('.md-subheader.hide').show();this.scope.pessoa.telefones=this.telefones;this.util.toast('Telefone adicionado, salve para garantir as modificações.');this.timeout(function(){self.scope.telefone=self.service.getEstruturaTelefone();$("#telefone_numero").val('')},300)}else if(tamanhoTelefone>11){this.util.toast('Ambos os campos devem ser preenchidos para adicionar um telefone.')}}
removerTelefone(telefone,index){var self=this;if(this.util.isNovoObjeto(telefone)){this.telefones.splice(index,1)}else{this.telefoneService.remover(telefone,!0).then((result)=>{self.telefones.splice(index,1);if(self.telefones.length>0){$('md-divider.hide').show();$('.md-subheader.hide').show()}else{$('md-divider.hide').hide();$('.md-subheader.hide').hide()}})}}
initMapa(){var lat;var lng;if(this.util.isVazio(this.scope.pessoa.endereco.latitude)){lat=-26.930232;lng=-48.684180}else{lat=parseFloat(this.scope.pessoa.endereco.latitude);lng=parseFloat(this.scope.pessoa.endereco.longitude)}
if(typeof this.mapa.remove==="function"){this.mapa.remove()}
this.mapa=L.map('mapa').setView([lat,lng],16);this.mapa.scrollWheelZoom.disable();L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}',{attribution:'Erudio Map by &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',maxZoom:24,id:'mapbox.streets',accessToken:'pk.eyJ1IjoiY3Jpc3RpYW5vc2llYmVydCIsImEiOiJjajRlaXlseDQwNDNhMndydjNqYzlqOWtyIn0.MQqg-LSABfmy1v8-EIpBGg'}).addTo(this.mapa);this.marker=L.marker([lat,lng]).addTo(this.mapa);this.mapa.on('click',this.adicionarMarcador.bind(this))}
adicionarMarcador(event){this.mapa.removeLayer(this.marker);var self=this;this.marker=L.marker([event.latlng.lat,event.latlng.lng]).addTo(this.mapa);this.marker.bindPopup('<div class="map-popup-content"><strong>Este é o endereço desejado?</strong><br /><br /><button id="btnMapaSim" class="material-btn">Sim</md-button><button class="material-btn">Não</md-button></div>').openPopup();$("#btnMapaSim").on('click',function(ev){ev.preventDefault();self.confirmaLatLng(event)})}
confirmaLatLng(event){var lt=parseFloat(event.latlng.lat).toFixed(6);var ln=parseFloat(event.latlng.lng).toFixed(6);this.scope.pessoa.endereco.latitude=parseFloat(lt);this.scope.pessoa.endereco.longitude=parseFloat(ln);this.mapa.closePopup()}
preencheCEP(){var self=this;this.timeout(function(){$("input[name=cep]").change(function(){self.buscaCEP()})},500)}
buscaCEP(){if(!this.util.isVazio(this.scope.pessoa.endereco.cep)&&this.scope.pessoa.endereco.cep.length===8){this.util.buscaCEP(this.scope.pessoa.endereco.cep).then((addr)=>{if(!this.util.isVazio(addr.bairro)){this.scope.pessoa.endereco.bairro=addr.bairro;this.util.validarCampos()}
if(!this.util.isVazio(addr.logradouro)){this.scope.pessoa.endereco.logradouro=addr.logradouro;this.util.validarCampos()}
if(!this.util.isVazio(addr.uf)){this.estados.forEach((estado)=>{if(estado.sigla===addr.uf){this.scope.pessoa.endereco.cidade.estado.id=estado.id;this.util.validarCampos();if(!this.util.isVazio(addr.localidade)){this.cidadeService.getAll({nome:addr.localidade},!0).then((cidade)=>{this.scope.pessoa.endereco.cidade.id=cidade[0].id;this.cidade=cidade[0];this.nomeCidade=cidade[0].nome;this.util.validarCampos()})}}})}})}}
iniciar(){let permissao=this.verificarPermissao();var self=this;this.util.comPermissao();$('.btn-home').hide();this.attr=JSON.parse(sessionStorage.getItem('atribuicoes'));this.util.setTitulo(this.titulo);this.escrita=this.verificaEscrita();this.isAdmin=this.util.isAdmin();$(".fit-screen").unbind('scroll');this.timeout(()=>{this.validaCampo()},500);this.preparaForm();this.buscarPessoa();this.timeout(()=>{$("input").keypress(function(event){var tecla=(window.event)?event.keyCode:event.which;if(tecla===13){self.salvar()}})},1000);this.util.inicializar()}}
PerfilController.$inject=["PessoaService","Util","ErudioConfig","$routeParams","$timeout","EstadoService","CidadeService","EnderecoService","TelefoneService","$scope","BeneficioService","NecessidadeEspecialService","UsuarioService","$http"];angular.module('PerfilController',['ngMaterial','util','erudioConfig']).controller('PerfilController',PerfilController)})();